### ISSUE TITLE
UE4 Asserts not captured on Android

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unreal#1]

**Comment by bruno-garcia** [comment]
>  Facing this behavior when running the debug build on Android device - even though the app crashes Sentry doesn't capture anything
>  For some reason SDK acts like this only with asserts while the crashes are logged as expected 
>

**Comment by vtzay** [comment]
I facing with this on Android and IOS in Development Builds. App has been crashed by fatal log message.

**Comment by souredoutlook** [comment]
Hey @vtzay can you let us know exaclty how you're crashing? With Asserts or some other way? Could you try:
```
    char *ptr = 0;
    *ptr += 1;
```
?

**Comment by tustanivsky** [comment]
Hi @souredoutlook, this issue occurs only when using asserts. Here is the sample that is used in the UE plugin demo:
```
void USentryLibrary::Assert()
{
	char *ptr = nullptr;
	check(ptr != nullptr);
}
```
The snippet you've shared above crashes the app and the corresponding event captured by Sentry as expected in this case.

P.S. With sentry-java 6.0.0 problem still persists

**Comment by vtzay** [comment]
> Hey @vtzay can you let us know exaclty how you're crashing? With Asserts or some other way? Could you try:
> 
> ```
>     char *ptr = 0;
>     *ptr += 1;
> ```
> 
> ?

Yes it's working ok. 

We think it's possible to catch and send crashes on fatal logs using SDK calls.
Unreal may call some code on a non-main thread at the time of the crash before it exits.
For example, we can send a log message as Breadcrumb.
We may try to do this and can share if the result is successful.
