### ISSUE TITLE
Ability to Promote values from Unreal Crash Reporter to Sentry Tags

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#170]
What problem could Sentry solve that it doesn't?
We would like to use values such as Unreal.engine_mode and unreal.build_configuration as a tag

Can we have a method to promote these values?

**Comment by tustanivsky** [comment]
@Edstub207 can you please elaborate a bit more on how you'd think the corresponding API should look? It's already possible to add new tags with the `USentrySubsystem::SetTag` method and the values mentioned above can be obtained using `FGenericPlatformMisc::GetEngineMode()` and `FApp::GetBuildConfiguration` respectively.

**Comment by Edstub207** [comment]
@tustanivsky It would be nice to not have it duplicated, so the ability to promote values I guess within the settings would be cool. Although, just adding via the SetTag method is possible
