### ISSUE TITLE
Faster Symbol Upload Time

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#197]
What problem could Sentry solve that it doesn't?
Currently, uploading Symbols to Sentry for an Unreal Project takes a very long time - Adding ~30 minutes onto the compile time. Which when we are wanting to have quick build turn arounds, isn't ideal. 

Is there a way to speed this up somehow?

**Comment by bitsandfoxes** [comment]
It is possible to upload the symbols after the fact. So in your case, if you don't need the symbols you could upload them when you know you're going to need them?

**Comment by Edstub207** [comment]
@bitsandfoxes Yeah I've been testing different methods over the past day or so, sadly when we tried to upload symbols from a SymStore I set up yesterday it didn't work. 

Part of the problem I'm having right now is even when symbols *are* uploaded they aren't resolving properly on Sentry. We get some info, but nowhere near as much as we should. I've been trying to establish differences between our projects, and one of them is the usage of the plugin integration of Sentry. But that shouldn't have an impact on stuff like this.

**Comment by bitsandfoxes** [comment]
> To be clear, we want the symbols for every build generated on our build farm

It sounds to me that setting this up as a [symbol server]( https://docs.sentry.io/platforms/native/data-management/debug-files/symbol-servers/) might be the answer to your problem?

**Comment by Edstub207** [comment]
@bitsandfoxes Yeah we've been looking into that, however, the symbol server isn't uploading to Sentry. 

I do have a support ticket with Sentry open for that though.

**Comment by Edstub207** [comment]
Update: Tested this today, still didn't really help, hit two hours on the upload. and abandoned it. Although, it looks like Sentry doesn't support compressed symbols, which is what caused one of our problems.

**Comment by bitsandfoxes** [comment]
> Yeah we've been looking into that, however, the symbol server isn't uploading to Sentry.

Could you clarify what you mean by that? Sentry is not pulling the symbols from your symbol server when it tries to symbolicate an event?

**Comment by Edstub207** [comment]
@bitsandfoxes, we're having problems with CAB Compressed symbols being upload to Sentry, when we push using the Sentry CLI similarly to what the plugin does. We where pointed towards https://github.com/getsentry/symbolicator however not sure if that's needed when using Sentry.io or not. 

Non compressed symbols upload fine but no crashes resolve. It's really weird, trying to pop on a call with Sentry support to work out what's going on but not heard anything from them yet.

**Comment by Edstub207** [comment]
Looping back to this in-case others see it, it seems to be caused by Sentry CLI not supporting compressed symbols or files over 2GB - So the automatic upload logic might be somewhat limited (At least on UE5 where we're seeing >2GB PDBs) 

@bitsandfoxes FYI

**Comment by bitsandfoxes** [comment]
Thanks for the update!
AFAIK the file size limitation targets the direct upload only. So if you were to provide Sentry with a symbol server to pull these symbols from this should be a working workaround.
