### ISSUE TITLE
Sentry Crash Reports don't have any User Data (though regular messages do)

### ISSUE THREAD

**Issue by PlaysideTrav** [getsentry/sentry-unreal#214]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) (sentry.native@v0.4.15)

Which version of the SDK?
0.1.0 and 0.2.0 (have tested with both)

How did you install the package? (Git-URL, Assetstore)
Downloaded a release package .zip from github

Which version of Unreal?
4.26.2 (I know 0.2.0 is not intended with Unreal 4.26 so I tested it with the 0.1.0 version and the below result is the same)

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Windows standalone build (we don't use sentry if the editor is running)

### Steps to Reproduce

1. Set the user in Sentry during UGameInstance::Init()
2. Crash the game
3. Check the crash in Sentry to read the user data

### Expected Result

The crash in Sentry would have the user data info included.

### Actual Result
There is no user data attached to the crash log event.

## Additional Info
Regular events/captured messages have the correct user data attached (see picture below) to confirm the user is being set in Sentry.
I've also tried setting the user directly and by using the config version.
Here is the code used to set the user:

```
void UMyGameInstance::init_sentry_user()
{
    auto id = player_id.ToDebugString();
    auto ip_adress = FString("{{auto}}");
    auto username = FString("Dev");
    
    // directly set the user
    USentryUser* User = NewObject<USentryUser>();
    User->SetIpAddress(ip_adress);
    User->SetId(id);
    User->SetUsername(username);
    
    GetSubsystem<USentrySubsystem>()->SetUser(User);
    
    // set the user in the crash reporter
    /* Test config version, also not working
    TSharedPtr<FJsonObject> sentry_config = MakeShareable(new FJsonObject);
    TSharedPtr<FJsonObject> user = MakeShareable(new FJsonObject);
    user->SetStringField("ip_address", ip_adress);
    user->SetStringField("id", id);
    user->SetStringField("username", username);
    sentry_config->SetObjectField("user", user);
    
    FString jsonConfig;
    TSharedRef<TJsonWriter<>> jsonWriter = TJsonWriterFactory<>::Create(&jsonConfig);
    FJsonSerializer::Serialize(sentry_config.ToSharedRef(), jsonWriter);
    
    FGenericCrashContext::SetGameData(TEXT("__sentry"), jsonConfig);
    */
}
```

### Any logs or screenshots
![image](https://user-images.githubusercontent.com/125942798/220253870-f11128b7-dd74-4537-bc38-4f51b707cd01.png)
![image](https://user-images.githubusercontent.com/125942798/220253886-4a27d3e1-cfdd-4845-8d08-ff5cd8db0265.png)

**Comment by tustanivsky** [comment]
@PlaysideTrav Thanks for reporting this issue, we'll check this on our end and get back to you

**Comment by tustanivsky** [comment]
Hey @PlaysideTrav, calling `GetSubsystem<USentrySubsystem>()->SetUser(User)` during the `UGameInstance::Init()` might be unreliable since the game instance's subsystems are actually initialized after the game instance itself. You can try moving this logic to some other place and set the user when `USentrySubsystem` is guaranteed to be ready (you can toggle its auto init in plugin settings btw).

**Comment by PlaysideTrav** [comment]
Hi @tustanivsky I've managed to get users working consistently now before your recommendation, but I might have to go back and implement what you said. Thanks for the tip and help!
