### ISSUE TITLE
Support Sentry Release Health Feature

### ISSUE THREAD

**Issue by vikram-saran-playside** [getsentry/sentry-unreal#230]
Sentry has a [Release Health feature](https://docs.sentry.io/product/releases/health/) feature which is not available in the Unreal SDK, however the Native C/C++ SDK supports it.

Please add this feature, as it would greatly improve our utility using Sentry with Unreal Engine.

**Comment by bitsandfoxes** [comment]
Thanks for reaching out! We'll definitely look into it.
