### ISSUE TITLE
Linux server fails to start due to libssl library loading errors

### ISSUE THREAD

**Issue by Tobias-Nilsson-Sharkmob** [getsentry/sentry-unreal#236]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
Latest on main (0.3.0)

How did you install the package? 
Manually

Which version of Unreal?
5.1.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
During the startup of a server on a Linux machine running **Ubuntu 22.04**

### Steps to Reproduce

1. Compile a server for an Unreal project targeting Linux with the Sentry plugin enabled
2. Start the server process on a Linux version such as **Ubuntu 22.04**

### Expected Result

The server should be able to startup & initialize properly

### Actual Result

`Binaries/Linux/Server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
`Failed with result 'exit-code'.`

**Comment by Edstub207** [comment]
@Tobias-Nilsson-Sharkmob Something I forgot to ask when we talked about this earlier that might be usedful to the Sentry team is if this was cross-compiled from Windows to Linux?

**Comment by sharkmob-ermin** [comment]
Just to clarify, its not an issue with `sentry-unreal`, but with `sentry-native`. The crashpad handler had dependencies to **libssl.so.1.1** which has since been removed after the `0.6.0` release.
What we did to test this theory out was we compiled the sentry-native on the commit **7abe8d1b2657110c0d10eb035827c7ebe3a0406c** and with that the crashpad worked as it should even on Ubuntu 22.04

**Comment by Swatinem** [comment]
As @sharkmob-ermin pointed out:

> The crashpad handler had dependencies to **libssl.so.1.1** which has since been removed after the `0.6.0` release.

Using the crashpad backend will now link to `libcurl` instead. I believe just updating to the latest release should work. In case the `sentry-native` version is hardcoded in `sentry-unreal`, this would need to be bumped. CC @bitsandfoxes

**Comment by bitsandfoxes** [comment]
Hey @sharkmob-ermin. Thanks for already doing the digging for us. We'll release a new version of `sentry-native` and bump it in the Unreal SDK.

**Comment by sharkmob-ermin** [comment]
You're welcome @bitsandfoxes. Thank you for bumping the release so quickly, we appreciate it!
