### ISSUE TITLE
Compile error on Mac

### ISSUE THREAD

**Issue by sapaczb** [getsentry/sentry-unreal#255]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
0.0.4

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unreal?
5.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
MacOS Monterey
Xcode (14.2)

### Steps to Reproduce
1. Create project using UE 5.1 (retail)
2. Add sentry 0.0.4 to PathToGame/Plugins
3. Generate workspace
4. Open workspace and compile project
### Expected Result
Project compiles and UE Editor opens

### Actual Result
Project fails to compile

### Any logs or screenshots
![image](https://user-images.githubusercontent.com/16910841/232175173-b40dd762-3e24-434b-9285-fc53178ea736.png)

**Comment by sapaczb** [comment]
This also occurs when you package for iOS

**Comment by tustanivsky** [comment]
The fix for this issue was already merged (https://github.com/getsentry/sentry-cocoa/pull/2860), so now we're just waiting for the next `sentry-cocoa` release in order to bump it in the UE plugin accordingly.

**Comment by tustanivsky** [comment]
The fix for this problem was merged into `main` and will be available in the next plugin release.

**Comment by ODevJon** [comment]
Hello, I was also having this issue building on macOS with the 0.4.0 release, and including the changes made to Sentry.Build.cs did fix the `COCOAPODS not defined` error. But I'm still seeing the errors related to `sampleRate` in SentryTraceContext.h. 
  `no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]`
  `default property attribute 'assign' not appropriate for object [-Werror,-Wobjc-property-no-attribute]`
Is there another fix or workaround for these errors?
Thank you!

**Comment by tustanivsky** [comment]
> Hello, I was also having this issue building on macOS with the 0.4.0 release, and including the changes made to Sentry.Build.cs did fix the `COCOAPODS not defined` error. But I'm still seeing the errors related to `sampleRate` in SentryTraceContext.h. `no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]` `default property attribute 'assign' not appropriate for object [-Werror,-Wobjc-property-no-attribute]` Is there another fix or workaround for these errors? Thank you!

Adding `COCOAPODS` define to `Sentry.Build.cs` won't be enough here. The thing is that the second error you've described is related to `sentry-cocoa` (one of the plugin dependencies) which has to be updated as well.
