### ISSUE TITLE
Ability to turn on & off platforms/configurations from sending crashes to Sentry

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#262]
What problem could Sentry solve that it doesn't?
While we're currently waiting on #32 support, something that would be useful alongside this would to be able to turn off crashes for certain configurations or platforms, for example, we don't want to send Editor crashes to Sentry.

**Comment by bitsandfoxes** [comment]
That's a super-valid feature request! I'll take that into planning.
