### ISSUE TITLE
Linux Server unable to load libsentry.so

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#277]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
0.5.0

How did you install the package? (Git-URL, Assetstore)
Git release

Which version of Unreal?
5.1.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Linux Server

### Steps to Reproduce

1. Package a Linux server build with the Sentry plugin enabled
2. Run the Linux server build inside a container (Ubuntu 20.04)

### Expected Result

The server launches.

### Actual Result

The server fails to launch.

### Any logs or screenshots

I see an error message stating:

> error while loading shared libraries: libsentry.so: cannot open shared object file: No such file or directory

**Comment by riot-pmaconi** [comment]
This can be resolved by adding the following snippet to the Linux block inside Sentry.Build.cs::LoadThirdPartyLibrary()

`PublicRuntimeLibraryPaths.Add(BinariesPath);`

**Comment by bitsandfoxes** [comment]
Thanks for reporting the issue and also providing a fix for it!

**Comment by tustanivsky** [comment]
This might be already addressed in the scope of #249, I'll revisit this PR and double-check dependencies loading for Linux Server configuration.
