### ISSUE TITLE
Avoid precompiled binaries in the repo

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unreal#28]
It would be nice if we could avoid having binaries pushed in the repo, such as Android aar/jar files, crashpad_handler executables, etc. Ideally, the files should be downloaded from their repositories with a script that can be run both locally & in CI before packaging (see #4) and check a hard-coded checksum. Updating to a newer dependency would be just updating the tag & checksum in this script. 

Alternatively, we could run the build in CI in this repo, as we do for sentry-unity, but that complicates things here a bit and is slower so unless there's strong incentive to do that, having a script should be enough IMO.

**Comment by bruno-garcia** [comment]
We also need a process of updating these dependencies
