### ISSUE TITLE
Linux crash reports do not respect sentry_options_set_http_proxy

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#282]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
0.5.0

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.1.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Linux server

### Steps to Reproduce

1. Configure an http proxy via sentry_options_set_http_proxy
2. Verify that SentrySubsystem->CaptureMessage() correctly sends a message through the proxy
3. Trigger a crash

### Expected Result

The crash is routed through the proxy and reaches Sentry

### Actual Result

The crash does not get routed through the proxy and never reaches Sentry

**Comment by riot-pmaconi** [comment]
I believe this issue in sentry-native is the cause: https://github.com/getsentry/sentry-native/issues/788. Is there any workaround available?

**Comment by tustanivsky** [comment]
Maybe @supervacuus can help with this one?

**Comment by supervacuus** [comment]
Instead of proposing a workaround, I suggest implementing this in our crashpad fork. This is only a matter of prioritization :-)

**Comment by tustanivsky** [comment]
The fix (https://github.com/getsentry/sentry-native/pull/847) should be available after we bump `sentry-native` version for the UE plugin.

**Comment by supervacuus** [comment]
> The fix ([getsentry/sentry-native#847](https://github.com/getsentry/sentry-native/pull/847)) should be available after we bump `sentry-native` version for the UE plugin.

[0.6.3](https://github.com/getsentry/sentry-native/releases/tag/0.6.3) was just released, so you should have a bump PR soonish in your inbox.

**Comment by bitsandfoxes** [comment]
Will be part of the next release!
