### ISSUE TITLE
Missing ability to add stacktraces to CaptureEvent (or CaptureMessage?)

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#295]
Right now the SentrySubsystem exposes ways to capture events or messages, but does not provide a way to add a stacktrace to the event that is emitted. 

The APIs seem to exist and function just fine if I manually add the following between event creation and capture, though I only tested on a Windows desktop:

```
sentry_value_t exc = sentry_value_new_exception(TCHAR_TO_ANSI(*message), TCHAR_TO_ANSI(*message));
sentry_value_set_stacktrace(exc, nullptr, 0);
sentry_event_add_exception(sentryEvent, exc);
```

**Comment by tustanivsky** [comment]
Thank you for raising this! We'll check what options we have for adding stack trace to captured events on other platforms as well and consider adding it in some future plugin releases.
