### ISSUE TITLE
Unable to set Release

### ISSUE THREAD

**Issue by highlyunavailable** [getsentry/sentry-unreal#31]
I'm unable to set the Release value of my Unreal product in the SDK. I've got the version number I want to use, and I could manually add it to the crash reporter data, but I'd love it if there was a way to initialize the Sentry subsystem with the release so that it automatically posted it correctly with each event. This is even more important on non-desktop platforms as the crash reporter isn't used.

**Comment by bruno-garcia** [comment]
This is something we want to look into but we don't have a timeline just yet. Our goal was to get the plugin and support Mobile, Desktop, Web before we get into Consoles.

**Comment by bruno-garcia** [comment]
This should be possible to be provided via initialization. Thanks for raising
