### ISSUE TITLE
Unreal iOS Shipping Build | Unable to Build related to Bitcode

### ISSUE THREAD

**Issue by buihuuloc** [getsentry/sentry-unreal#310]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
* Latest SDK 0.7

How did you install the package? (Git-URL, Assetstore)
* Download from github
*
Which version of Unreal?
* 5.0

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?

### Steps to Reproduce
* Build shipping iOS
* Related to bitcode
* Check the image below
<img width="1922" alt="Screenshot 2023-06-21 at 15 26 57" src="https://github.com/getsentry/sentry-unreal/assets/1252560/8e396556-74f2-4c41-aa8f-cc6a298eabbd">

### Expected Result
* Able to build

What you thought would happen.

**Comment by tustanivsky** [comment]
@buihuuloc Did you enable the `Support bitcode in Shipping` option in `Project Settings -> iOS`?

**Comment by buihuuloc** [comment]
Yes

**Comment by tustanivsky** [comment]
> Yes

I think disabling the bitcode should do the trick unless you have any other reasons to keep turned on

**Comment by buihuuloc** [comment]
Yeah. It seems working. 
Thanks @tustanivsky
