### ISSUE TITLE
Reach parity in information collected from the automatic crash collection and crash reporter flows

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#336]
What problem could Sentry solve that it doesn't?

Issues created by the Unreal crash reporter contain a lot more information in Sentry than issues created by the sentry-unreal integration. This information is visible under an 'Unreal' header on the issue and the source seems to be the CrashContext.runtime-xml file that Unreal generates. The sentry-unreal integration has a much more sparse 'Unreal Engine' header with some details about the crash. 

It'd be great if sentry-unreal could provide the same level of detail as the crash reporter.

**Comment by tustanivsky** [comment]
@riot-pmaconi Thank you, this is something we will look into.

**Comment by tustanivsky** [comment]
UPD: #342 makes an attempt to unify crash information collected by the default crash reporter and `sentry-native`.

@riot-pmaconi Please feel free to suggest any other properties that might be useful to extract from the `CrashContext.runtime-xml` in order to display them on the issue page.

**Comment by laurentcau** [comment]
`<CommandLine>` property is useful for us because we use unreal exe as subprocess.

RHI properties are usefull because they contain the GPU properties used. (the sentry Graphics Processing Unit is not the one used by unreal, the integrated GPU in my case)
example:
```
<RHI.IntegratedGPU>false</RHI.IntegratedGPU>
<RHI.DriverDenylisted>false</RHI.DriverDenylisted>
<RHI.D3DDebug>false</RHI.D3DDebug>
<RHI.DRED>false</RHI.DRED>
<RHI.DREDMarkersOnly>false</RHI.DREDMarkersOnly>
<RHI.DREDContext>false</RHI.DREDContext>
<RHI.Aftermath>true</RHI.Aftermath>
<RHI.RHIName>D3D12</RHI.RHIName>
<RHI.AdapterName>NVIDIA RTX 3500 Ada Generation Laptop GPU</RHI.AdapterName>
<RHI.UserDriverVersion>573.57</RHI.UserDriverVersion>
<RHI.InternalDriverVersion>32.0.15.7357</RHI.InternalDriverVersion>
<RHI.DriverDate>7-9-2025</RHI.DriverDate>
<RHI.FeatureLevel>SM6</RHI.FeatureLevel>
<RHI.GPUVendor>NVIDIA</RHI.GPUVendor>
<RHI.DeviceId>27BB</RHI.DeviceId>
<DeviceProfile.Name>Windows</DeviceProfile.Name>
```
