### ISSUE TITLE
Unable to turn off Sentry-Native on Linux & Windows 

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#353]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
https://github.com/getsentry/sentry-unreal/commit/edf4751aa8edbf83addfc142884d43ec31a3cba1

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Compilation of Client. 

### Steps to Reproduce

1. Navigate to the Sentry.build.cs file 
2. Disable Sentry-Native (Turning USE_SENTRY_NATIVE to 0) for both the Linux and Windows Platform
3. Compile 

### Expected Result

No compilation failures. 

### Actual Result

Multiple compilation failures

**Comment by Edstub207** [comment]
> @Edstub207 What's the reason you're trying to exclude plugin implementation for Win/Linux from the build? It should be a straightforward fix though I'd like to understand the motivation behind this

@tustanivsky It's very closely tied to https://github.com/getsentry/sentry-unreal/issues/354 where we just aren't getting reliable callstacks in Sentry. So we want to revert back to using the Crash Reporter for now to see if that improves things. 

Admittedly, it's not clear what's Sentry-Native and what's part of the generic plugin.

**Comment by tustanivsky** [comment]
> @tustanivsky It's very closely tied to #354 where we just aren't getting reliable callstacks in Sentry. So we want to revert back to using the Crash Reporter for now to see if that improves things.

I believe disabling the `Initialize SDK automatically` option in the plugin setting should be enough for switching back to the crash reporter testing unless you're willing to use any other plugin functionality at the same time (i.e. sending messages to Sentry manually on certain occasions).

> Admittedly, it's not clear what's Sentry-Native and what's part of the generic plugin right now, a lot seems to be guarded by Sentry-Native?

Basically, the UE plugin is a wrapper for a bunch of other Sentry SDKs (`sentry-native` for Win/Linux, `sentry-jave` for Android and `sentry-cocoa` for macOS/iOS). The generic part of it provides Unreal-friendly APIs allowing to initialize the underlying native SDKs and enrich captured events with some data specific to the engine. The actual crash/event capturing is fully handled on the native SDKs side and we're somewhat limited in terms of altering their behavior.

Speaking of Win/Linux implementation the `USE_SENTRY_NATIVE` definition prevents scripts in `Sentry/Source/Private/Desktop` from being compiled while using the plugin on Mac.

**Comment by tustanivsky** [comment]
@Edstub207 I've added some extra `USE_SENTRY_NATIVE` checks so now disabling it programmatically shouldn't cause any trouble.
