### ISSUE TITLE
Unusable Sentry Callstacks when using Sentry-Native

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#354]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
https://github.com/getsentry/sentry-unreal/commit/edf4751aa8edbf83addfc142884d43ec31a3cba1

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Windows & Linux

### Steps to Reproduce

1. Upload symbols to Sentry
2. Crash the Server or Game Client 

### Expected Result
The callstack is usable and matches the callstack available on the machine

### Actual Result
Callstacks are inconsistent and unable to be used 

From my understanding based on another discussion elsewhere, callstacks have been more  usable when using Google Breakpad. 

We'd expect the callstacks to match Unreal's Crash Reporter, identically. 

I also wonder if this is related to the different size in crash dumps @tustanivsky mentioned here > https://github.com/getsentry/sentry-unreal/issues/329#issuecomment-1641553206

**Comment by Edstub207** [comment]
Hello @tustanivsky here is an example from today, using Unreal Engine 5.2.1. 

Callstack from Unreal.log which we'd expect in Sentry

`[2023.08.21-11.20.25:964][739]LogSentrySdk: serializing envelope into buffer
[2023.08.21-11.20.25:964][739]LogSentrySdk: handing control over to crashpad
CommonUnixCrashHandler: Signal=11
[2023.08.21-11.20.26:002][739]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to write memory at address 0x0000000000000003

[2023.08.21-11.20.26:002][739]LogCore: Fatal error: [File:.\Runtime/Engine/Private/UnrealEngine.cpp] [Line: 10120] 
Crashing the gamethread at your request
0x000000000dbf82d1 RedactedServer!UEngine::PerformError(char16_t const*, FOutputDevice&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/UnrealEngine.cpp:10120]
0x000000000dbeca51 RedactedServer!UEngine::HandleDebugCommand(char16_t const*, FOutputDevice&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/UnrealEngine.cpp:7953]
0x000000000dbde362 RedactedServer!UEngine::Exec_Dev(UWorld*, char16_t const*, FOutputDevice&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/UnrealEngine.cpp:5011]
0x000000000dbdc652 RedactedServer!UEngine::Exec(UWorld*, char16_t const*, FOutputDevice&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/UnrealEngine.cpp:4628]
0x000000000d1048aa RedactedServer!UGameEngine::Exec(UWorld*, char16_t const*, FOutputDevice&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/GameEngine.cpp:1523]
0x000000000d75488e RedactedServer!UPlayer::ConsoleCommand(FString const&, bool) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/Player.cpp:53]
0x000000000d79500b RedactedServer!APlayerController::ConsoleCommand(FString const&, bool) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/PlayerController.cpp:479]
0x000000000d799b15 RedactedServer!APlayerController::ServerExecRPC_Implementation(FString const&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/PlayerController.cpp:1866]
0x000000000d78b280 RedactedServer!APlayerController::execServerExecRPC(UObject*, FFrame&, void*) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/../../Redacted/Intermediate/Build/Linux/RedactedServer/Inc/Engine/UHT/PlayerController.gen.cpp:1742]
0x00000000091b6767 RedactedServer!UFunction::Invoke(UObject*, FFrame&, void*) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/CoreUObject/Private/UObject/Class.cpp:6449]
0x00000000093989b6 RedactedServer!UObject::ProcessEvent(UFunction*, void*) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:2226]
0x000000000ca79c3a RedactedServer!AActor::ProcessEvent(UFunction*, void*) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/Actor.cpp:1245]
0x000000000d01264a RedactedServer!FObjectReplicator::ReceivedRPC(FNetBitReader&, FReplicationFlags const&, FFieldNetCache const*, bool, bool&, TSet<FNetworkGUID, DefaultKeyFuncs<FNetworkGUID, false>, FDefaultSetAllocator>&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataReplication.cpp:1393]
0x000000000d010b5a RedactedServer!FObjectReplicator::ReceivedBunch(FNetBitReader&, FReplicationFlags const&, bool, bool&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataReplication.cpp:1166]
0x000000000cfe3d52 RedactedServer!UActorChannel::ProcessBunch(FInBunch&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataChannel.cpp:3125]
0x000000000cfe5a44 RedactedServer!UActorChannel::ReceivedBunch(FInBunch&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataChannel.cpp:2965]
0x000000000cfd5bd2 RedactedServer!UChannel::ReceivedSequencedBunch(FInBunch&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataChannel.cpp:558]
0x000000000cfd7bd9 RedactedServer!UChannel::ReceivedNextBunch(FInBunch&, bool&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataChannel.cpp:1022]
0x000000000cfd6041 RedactedServer!UChannel::ReceivedRawBunch(FInBunch&, bool&) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/DataChannel.cpp:670]
0x000000000d48ff77 RedactedServer!UNetConnection::ReceivedPacket(FBitReader&, bool) [E:/Horde/Work/RedactedInc/Sync/Engine/Source/./Runtime/Engine/Private/NetConnection.cpp:3530]
0x000000000d48d941 RedactedServer!UNetConnection::ReceivedRawPacket(v`


Sentry Callstack:

![image](https://github.com/getsentry/sentry-unreal/assets/13305475/27d06c8b-d31f-47d5-921e-445c0442df2c)

**Comment by tustanivsky** [comment]
Did you try to compare it with a crash callstack captured by `Crash Reporter` (one displayed at the top of Sentry page)? Crash reporter additionally puts the same callstack into `Additional info` section, though it's not our point of interest here - from the screenshot above my first guess is that something is wrong with crash symbolication.

**Comment by Edstub207** [comment]
@tustanivsky I believe the sentry-cli was throwing out some files when uploading the symbols that should have been uploaded. Will be investigated further next week

**Comment by Edstub207** [comment]
Closing this issue - I believe this has been resolved and was a setup issue.
