### ISSUE TITLE
Difficulty in specifying DSN

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#357]
### Environment

How do you use Sentry?

sentry.io

Which version of the SDK?

0.6.0

How did you install the package? (Git-URL, Assetstore)

Git

Which version of Unreal?

5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?

Windows player

### Steps to Reproduce

1. Specify the DSN in DefaultEngine.ini in the form of "https://hash@otherhash.ingest.sentry.io/numbers"

### Expected Result

1. Sentry inits using the DSN.

### Actual Result

1. Sentry tries to init the DSN as `https:`. The forward slashes seem to be treated as a comment and truncate the rest of the URL.

I've also tried a few workarounds to get things to parse correctly. I replaced the // with \u002f\u002f, but sentry-native rejects the unicode slashes in init. I tried stripping https:// from the setting and that was also rejected by sentry-native. 

Ultimately, I edited the desktop subsystem locally to insert https:// and removed it from the settings file. Is there some other way to configure this without modifying the plugin?

**Comment by tustanivsky** [comment]
@riot-pmaconi Just wanted to clarify how exactly did you specify the DSN value - via Sentry plugin settings menu in the editor or by editing `DefaultEngine.ini` file directly (i.e. manually, with some CI-script etc.)?

**Comment by riot-pmaconi** [comment]
@tustanivsky I've tried both through the settings dialog and manually tweaking it.

**Comment by riot-pmaconi** [comment]
I'm only able to repro this when building in CI, so closing the issue under the assumption that it's something in my own build flow instead of a problem with the plugin
