### ISSUE TITLE
Sentry Automatic Crash Reporting is still enabled on Linux after turning it off 

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#358]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
https://github.com/getsentry/sentry-unreal/releases/tag/0.6.0

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.2.1
Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Linux

### Steps to Reproduce
1. Have the below config without the Unreal crash reporter staging:
```
EnableBuildTargets=(bEnableClient=True,bEnableGame=False,bEnableEditor=False,bEnableServer=True,bEnableProgram=False)
EnableAutoCrashCapturing=False
EnableBuildConfigurations=(bEnableDebug=False,bEnableDebugGame=False,bEnableDevelopment=True,bEnableTest=True,bEnableShipping=True)
```

1. Crash the server 
### Expected Result
No Crash is tracked

### Actual Result
Observe the crash is still tracked in Sentry even though it shouldn't be (Crash Reporter isn't staged, therefore, the only way it's being tracked is via the plugin) 

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by tustanivsky** [comment]
@Edstub207 `EnableAutoCrashCapturing` option alters the plugin's crash-capturing behavior only for UE 5.2+ on Windows. Starting from this particular engine version it becomes possible to disable SEH which intercepts crashes by default and prevents third-party tools like Sentry from doing that. 

Note that on Windows the default `Crash Reporter` tool is still recommended for older engine versions (prior to UE 5.2).

On Linux plugin tries to capture crashes automatically regardless of the `EnableAutoCrashCapturing` value so the only way to stop crash capturing is to disable plugin initialization completely (uncheck the `InitAutomatically` option).

**Comment by Edstub207** [comment]
@tustanivsky Thanks for the clarity, we don't actually have InitAutomatically set, we have a module which sets up a few tags and then initializes. 

I assume if we turned bEnableServer to false it wouldn't track the Linux server crashes? Has anything changed with the Linux Server crash collection recently? This is the main config we're having #354 as far as I'm aware. 

Do you remember if it's possible to use the CrashReporter on Linux?

**Comment by tustanivsky** [comment]
> I assume if we turned bEnableServer to false it wouldn't track the Linux server crashes? Has anything changed with the Linux Server crash collection recently? This is the main config we're having https://github.com/getsentry/sentry-unreal/issues/354 as far as I'm aware.

Yes, disabling `bEnableServer ` should prevent crashes from being captured for Server targets. A corresponding internal check runs right before initializing the plugin, so you should be all set with it.

> Do you remember if it's possible to use the CrashReporter on Linux?

Yes, you should be able to use crash reporter on all desktop platforms.

**Comment by Edstub207** [comment]
@tustanivsky Thanks for the clarity, is there a reason that EnableAutoCrashCapturing isn't a global flag?

**Comment by tustanivsky** [comment]
> @tustanivsky Thanks for the clarity, is there a reason that EnableAutoCrashCapturing isn't a global flag?

Yes, `EnableAutoCrashCapturing` flag is very specific to UE 5.2+ (Windows) and only determines [whether SEH should be disabled or not](https://github.com/getsentry/sentry-unreal/blob/30be44ef6a0b8cbd4c2913d6baf595f25d0365f0/plugin-dev/Source/Sentry/Private/Desktop/SentrySubsystemDesktop.cpp#L143C29-L143C29).

Although now I got your point regarding the confusion this flag name might cause. Apparently it's configured via the editor's settings menu most of the time where things are a bit more clear:

![image](https://github.com/getsentry/sentry-unreal/assets/3168564/c9cf4896-abf1-4374-ab28-be12dd0c10fd)

We can consider renaming it (i.e. `disableSEH`), though keep in mind that could be a breaking change for those who initialize the plugin manually in C++/BP.

**Comment by Edstub207** [comment]
@tustanivsky yeah I agree, it should be clearer because I was confused as to why Sentry crashes for the Linux Server where still being tracked when it was disabled. 

I'm not sure if saying something like disableSEH would be clear enough either. For example, I don't know what SEH is.
