### ISSUE TITLE
Incorrect stack trace attached to CaptureMessage events on Android

### ISSUE THREAD

**Issue by bmantas** [getsentry/sentry-unreal#361]
### Environment

How do you use Sentry?
self-hosted/on-premise (21.12.0)

Which version of the SDK?
0.8.0

How did you install the package? 
Git-URL

Which version of Unreal?
5.1.4

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Call USentrySubsystem::CaptureMessage(...)

### Expected Result

Correct stack trace attached to sentry message report

### Actual Result

stack trace that gets attached:
```
at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
at java.lang.Thread.getStackTrace(Thread.java:1841)
```

**Comment by tustanivsky** [comment]
@bmantas After taking a closer look at this it seems to be a current limitation of the Sentry Android SDK which plugin uses under the hood. For all non-crash events captured with `CaptureMessage`/`CaptureEvent` stack trace is missing the native C++ part and contains only the above lines from Java layer. At the same time crashes should have a proper call stack attached.

**Comment by tustanivsky** [comment]
I've added the corresponding notice to README.md #366
