### ISSUE TITLE
Crashpad Support on Windows

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#374]
What problem could Sentry solve that it doesn't?

It looks like the most recent release switches to breakpad on Windows and requires a relaunch to submit crash reports. Is there a way to get crashpad back for Windows? The requirement of an extra launch is enough of a loss in functionality that I'd be likely to stop using the plugin on Windows and just rely on the crash report client.

**Comment by tustanivsky** [comment]
@riot-pmaconi Switching to breakpad on Windows is a temporary solution while we're still discovering options allowing users to select which crash capturing backend to use (see #363 for some extra context). Most likely there will be two separate plugin versions available - one with `crashpad` and another with `breakpad` (for UE Marketplace). That's a high-priority task for us so I believe the corresponding changes will be introduced in the very next release.
