### ISSUE TITLE
Support immediate crash uploads on desktop.

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-unreal#380]
We are in the process of migrating from our custom Unreal Sentry client which we have been using for a few years, to your official one.
I was surprised to see that even though you do make use of unreal's
`FPlatformMisc::SetCrashHandlingType(ECrashHandlingType::Disabled)`  (from our PR https://github.com/EpicGames/UnrealEngine/pull/7976), crashes are only uploaded on the next run.

Contrast this with our plugin, where upload is immediate (we use CrashPad for both windows and linux builds)

https://github.com/mainframeindustries/UE4SentryClientPlugin/blob/3a3b8600c99135a17c18ab2a2fbd44df32ba6590/Source/SentryClient/Private/SentryClientModule.cpp#L387

I realize this is due to the choice of using BreakPad rather than CrashPad on windows, is there a good reason for that?

**Comment by bitsandfoxes** [comment]
Hey there! Thanks for reaching out. @tustanivsky [comment](https://github.com/getsentry/sentry-unreal/issues/374#issuecomment-1713273573) should answer your question.

Closing as duplicated.
