### ISSUE TITLE
Support logs as breadcrumbs

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-unreal#382]
We are in the process of migrating from our own unreal sentry plugin, which we have been using for a couple of years, 
https://github.com/mainframeindustries/UE4SentryClientPlugin

One nice feature it has it that it hooks into the unreal log handler to gather breadcrumbs that are added to sentry events:

https://github.com/mainframeindustries/UE4SentryClientPlugin/blob/3a3b8600c99135a17c18ab2a2fbd44df32ba6590/Source/SentryClient/Private/SentryClientModule.cpp#L450C1-L463

Is this something which could be easily added?

**Comment by tustanivsky** [comment]
@kristjanvalur Thank you for bringing it up! We've been using the above plugin as a reference earlier so adding logs as breadcrumbs is something we definitely want to look into.

**Comment by kristjanvalur** [comment]
> We've been using the above plugin as a reference earlier so adding logs as breadcrumbs is something we definitely want to look into.

Yes, I've noticed some striking similarities to my code 😉 .  It's been unmaintained for two years now, more or less, so switching over is a no-brainer for us.

**Comment by kristjanvalur** [comment]
Since I have you here, @tustanivsky , could I persuade you or anyone of your team to look at https://github.com/getsentry/sentry-unreal/discussions/383 ?
