### ISSUE TITLE
Ability to send crashes in a Push request 

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#384]
What problem could Sentry solve that it doesn't?
We've been told there is a method to send crashes using a push request - Is this something that could be done in the context of this plugin? 

EG: Once a crash dump is written, we push automatically? 

I can imagine it won't be possible as the process is terminated, but it's an idea to assist with a problem whereby we don't get crashes when an Unreal game server is wrapped in a Docker Container. 

https://docs.sentry.io/platforms/native/guides/minidumps/#minidump-integration

**Comment by bitsandfoxes** [comment]
I'm not entirely sure what you refer to with `push request`?

> a problem whereby we don't get crashes when an Unreal game server is wrapped in a Docker Container
Is that due to the switch to Breakpad? Or is that a problem when using Crashpad as well?

**Comment by Edstub207** [comment]
@bitsandfoxes I believe it's referencing this:
curl -X POST \
  'https://o578335.ingest.sentry.io/api/4505822672322560/minidump/?sentry_key=910c1bac91b5fc216bfe562ba33fbe71' \
  -F upload_file_minidump=@mini.dmp

As mentioned, I believe this won't be possible from a Sentry unreal perspective. 

Regarding Crashpad vs Breakpad, we currently only have Crashpad, we would have a similar problem with Breakpad because we don't keep persistence between containers, so once they crash the data will be gone.

**Comment by bitsandfoxes** [comment]
So to summarize: You have a unreal server running in a docker container, it crashes and then the container gets shut down - leaving no time for the crash to get reported. And you are looking for a way to do that manually?
What I could think of that could work is to set a path to a persistent path that survives the container shutting down?

**Comment by Edstub207** [comment]
@bitsandfoxes I'm not sure if this is still required - I believe this was back when a different method of sending crashes was being in use. At the moment, I'm not aware of any issues in the current implementation that would require this functionality.
