### ISSUE TITLE
trying to use the latest version of the plugin in 4.27.2 but it won't compile

### ISSUE THREAD

**Issue by ImagineTheGames** [getsentry/sentry-unreal#397]
I specifically need the android log fixes which aren't available in version 0.5 which is the last one that supported 4.27.2

trying to use the latest versions from 5.1 downported to 4.27 results in a lot of compiler errors...

**Comment by tustanivsky** [comment]
Thank you for raising this! We'll check it with 4.27 and see what can be done in order to fix those errors

**Comment by ImagineTheGames** [comment]
UnrealBuildTool: Error  : Unhandled exception: Source file ProjectName\Plugins\SentrySDK\Source\ThirdParty\Win64\Breakpad\bin\sentry.dll' does not exist

Seems like there is nothing in that ThirdParty folder when going to download the sentry-unreal source as zip file
