### ISSUE TITLE
Create a CI/CD pipeline for plugin packaging and testing

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-unreal#4]
In order to create a reproducible environment within which automated plugin packaging and testing can be performed an Unreal Engine container is required.

At the moment the most comprehensive solution out there is ue4-docker project (https://github.com/adamrehn/ue4-docker), which allows to build different types of Docker images for UE 4.20 and newer. For this particular use case the development image type is appropriate. Note that development images might take many gigabytes in size. 

Development images contain the Unreal Engine build tools and Editor, and there are strict EULA restrictions that govern their distribution ([https://unrealcontainers.com/docs/obtaining-images/eula-restrictions](https://unrealcontainers.com/docs/obtaining-images/eula-restrictions)).

Also, there are some official container images derived from ue4-docker project provided by Epic Games for UE 4.27 and newer (https://github.com/orgs/EpicGames/packages/container/package/unreal-engine)

Other considerations:
- Currently plugin doesn’t support Linux platform which can cause issues when using Linux containers
- Given images don’t support iOS and Android target platforms
- In order to package the plugin it should be placed into `Plugins/Sentry` folder of some UE project first

**Comment by vaind** [comment]
[Getting started guide](https://docs.unrealengine.com/5.0/en-US/quick-start-guide-for-using-container-images-in-unreal-engine/) - e.g. you need to connect your GH account to your EpicGames account or private repos on github.com/EpicGames won't work:

**Comment by vaind** [comment]
To verify the package contents, we could use the same approach as in sentry-unity: https://github.com/getsentry/sentry-unity/blob/76f0e16886974effca3f0df4aad03876b30d0d0b/.github/workflows/ci.yml#L291

**Comment by vaind** [comment]
> Note that development images might take many gigabytes in size.

hmm, the _slim_ version has 36 GB...

```
ghcr.io/epicgames/unreal-engine   dev-slim-5.0.2                         7af6dca020b7   2 weeks ago   36.1GB
```

Not so slim IMO. I've had a look and e.g. there's a python package cache (`site-packages`) of 11 GB in the UE installation directory.

Well I guess we get what's available and if it becomes an issue, we can have a look at slimming it down if possible.
