### ISSUE TITLE
Wizard uses DSN instead of Unreal endpoint

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unreal#402]
Project settings has a `unreal` endpoint, made for the UE Crash Reporter (it understand its format):
![image](https://github.com/getsentry/sentry-unreal/assets/1633368/4f5d6bd9-7d8b-4bb1-b1af-86b2cb1bc934)

But when creating a project, it seems we're using the DSN instead, which wouldn't work.
![image](https://github.com/getsentry/sentry-unreal/assets/1633368/398f0b1e-2eeb-4db4-b589-635ab10ae7d8)

Am I missing something or the setup process is broken?

**Comment by tustanivsky** [comment]
This looks like a mistake indeed - for CRC setup we have to use a separate UE endpoint and not the DSN. Thanks for bringing this up!

**Comment by tustanivsky** [comment]
For some reason even though the `___UNREAL_URL___` [value is used by the wizard](https://github.com/getsentry/sentry-docs/blob/553c8cf0468f8de34fda99763d5de92201683083/src/wizard/unreal/index.md?plain=1#L81C25-L81C25) the corresponding web page still displays the DSN instead. Works fine for the [CRC setup guide](https://docs.sentry.io/platforms/unreal/configuration/setup-crashreporter/#configure-the-crash-reporter-endpoint) though

**Comment by bruno-garcia** [comment]
@bitsandfoxes cc

**Comment by tustanivsky** [comment]
Similar issue here - https://github.com/getsentry/sentry/issues/71733

**Comment by bruno-garcia** [comment]
Forgot I had reported this 1 year ago. Got resolved after I came across it a second time: https://github.com/getsentry/sentry/issues/71733

Quite upsetting this `p0` was left here a whole year. Basically anyone who tried to create a Unreal package with the crash reporter failed to get Sentry running
