### ISSUE TITLE
When is 1.0 coming out?

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unreal#403]
Congrats on getting the package on the Unreal Engine Marketplace.

Curious when the SDK will be stable enough to deserve a 1.0 release?

**Comment by tustanivsky** [comment]
> Curious when the SDK will be stable enough to deserve a 1.0 release?

At this point we are just looking for initial feedback from users who acquired the plugin through the UE Marketplace which will help us understand whether the existing functionality, APIs, etc. work well and meet their expectations. The number of those is typically much higher compared to the amount of folks that came through GitHub so having their opinion might be quite valuable.

Also, there are some potential changes under discussion that may affect the plugin's backward compatibility which I believe makes them worth addressing first.

Having said the above, if nothing major comes up I think bumping the `sentry-unreal` version to 1.0 will be a matter of the upcoming weeks.
