### ISSUE TITLE
Missing Breadcrumbs on Linux Server Sentry Reports

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#425]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
0.8.0

How did you install the package? (Git-URL, Assetstore)
Github Download

Which version of Unreal?
5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Linux Server

### Steps to Reproduce

1. Build the Linux Server 
2. Run in a container
3. Crash the server

### Expected Result

No errors on reports

### Actual Result

![image](https://github.com/getsentry/sentry-unreal/assets/13305475/1db8d136-983d-4149-9dad-2393711080d0)

**Comment by tustanivsky** [comment]
Thank you for raising this! At first glance it looks like an issue on the backend side of things since we haven't touched breadcrumbs API quite for a while in the UE plugin however I'll check this on my side and let you know.
