### ISSUE TITLE
crashpad_handler: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RiotJoshuaGlazer** [getsentry/sentry-unreal#431]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
0.13

How did you install the package? (Git-URL, Assetstore)
github

Which version of Unreal?
5.3.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
This is a linux server

### Steps to Reproduce
build a linux server and run it on our version of linux.  check the unreal log and you'll see this error in the log and crashpad_handler doesn't start up.  I think it's trying to dynamically link a library even though PR 424 says everything should be statically linked?

### Expected Result
crashpad handler started up

### Actual Result
craashpad handler doesn't start up

### Any logs or screenshots
[2023.10.31-03.44.14:881][  0]LogSentrySdk: Sentry plugin auto initialization: true
[2023.10.31-03.44.14:881][  0]LogSentrySdk: using database path "/REDACTED/.sentry-native"
[2023.10.31-03.44.14:881][  0]LogSentrySdk: starting transport
[2023.10.31-03.44.14:881][  0]LogSentrySdk: starting backend
[2023.10.31-03.44.14:881][  0]LogSentrySdk: starting crashpad backend with handler "/REDACTED/crashpad_handler"
[2023.10.31-03.44.14:881][  0]LogSentrySdk: using minidump URL "https://REDACTED"
/REDACTED/crashpad_handler: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
[4481:4481:20231031,034414.885869:ERROR socket.cc:120] recvmsg: Connection reset by peer (104)
[2023.10.31-03.44.14:888][  0]LogSentrySdk: failed to start crashpad client handler
[2023.10.31-03.44.14:888][  0]LogSentrySdk: failed to initialize backend
[2023.10.31-03.44.14:888][  0]LogSentrySdk: `sentry_init` failed
[2023.10.31-03.44.14:888][  0]LogSentrySdk: shutting down transport
[2023.10.31-03.44.14:888][  0]LogSentrySdk: Sentry initialization completed with result 1 (0 on success).
[2023.10.31-03.44.14:888][  0]LogSentrySdk: Error: Sentry initialization failed.

**Comment by tustanivsky** [comment]
The corresponding notice regarding the required `Crashpad` dependencies installation was added in #455.

**Comment by riot-pmaconi** [comment]
Hi @tustanivsky - what is the reason for this additional dependency? Prior versions of crashpad provided by Sentry can be used in place of the current one without requiring it.

**Comment by tustanivsky** [comment]
> Hi @tustanivsky - what is the reason for this additional dependency? Prior versions of crashpad provided by Sentry can be used in place of the current one without requiring it.

In #424, #433 we've switched to static version of `sentry-native` which essentially introduced this additional dependency. The motivation to do so was addressing some users' build-related issues and proceeding with publishing the plugin to UE Marketplace.

@Swatinem @supervacuus is there something we can do to avoid the installation of extra packages like `libc++` here?

**Comment by supervacuus** [comment]
> > Hi @tustanivsky - what is the reason for this additional dependency? Prior versions of crashpad provided by Sentry can be used in place of the current one without requiring it.
> 
> In #424, #433 we've switched to static version of `sentry-native` which essentially introduced this additional dependency. The motivation to do so was addressing some users' build-related issues and proceeding with publishing the plugin to UE Marketplace.
> 
> @Swatinem @supervacuus is there something we can do to avoid the installation of extra packages like `libc++` here?

That means you are now building with `clang` instead of `gcc`.  `libc++` is just clang's standard library. I guess when you built the static version, you also changed the toolchain?

**Comment by tustanivsky** [comment]
> That means you are now building with clang instead of gcc. libc++ is just clang's standard library. I guess when you built the static version, you also changed the toolchain?

Thanks @supervacuus, you're absolutely right - we had to [switch](https://github.com/getsentry/sentry-unreal/pull/424/files#diff-6bfda834621f443cfd0458b3d7e814f00eb1c7d9f686f731e2513d2e6cd6eba7R10) to using `clang` to build static `sentry-native` libs that are compatible with UE on Linux.

I recall that this solution came from [here](https://github.com/getsentry/sentry-native/issues/531).

**Comment by supervacuus** [comment]
The static build only refers to the sentry library and the client parts of Crashpad. The `crashpad_handler` always dynamically relies on an installed standard library. Nothing changed in that regard except for the toolchain being used.
