### ISSUE TITLE
Sentry Crash Report delivers after it crashes again for the previous crash

### ISSUE THREAD

**Issue by ndsergeev** [getsentry/sentry-unreal#440]
### Environment

platform="Mac"
os="macOS 14.1 23B74"
cpu="GenuineIntel|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz"
physical mem="64 GB 2667 MHz DDR4", less than half used regarding event on sentry.io

**How do you use Sentry?**
Sentry SaaS (sentry.io)

**Which version of the SDK?, How did you install the package? (Git-URL, Assetstore)**
[14](https://github.com/getsentry/sentry-unreal/releases/download/0.14.0/sentry-unreal-0.14.0-engine5.3-github.zip)

**Additinal**
```ini
[CrashReportClient]
CrashReportClientVersion=1.0
DataRouterUrl="https://value1.ingest.sentry.io/api/value2/unreal/value3/"

[/Script/Sentry.SentrySettings]
Dsn="https://value3@value1.ingest.sentry.io/value2"
CrashReporterUrl="https://value1.ingest.sentry.io/api/value2/unreal/value3/"
EnableAutoLogAttachment=True
;I tried the one below, but it should not affect the behaviour I observe
UploadSymbolsAutomatically=False
```

**Which version of Unreal?**
config="Development"
buildversion="++UE5+Release-5.3-CL-28051148"
engineversion="5.3.1-28051148+++UE5+Release-5.3"

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Happens in Unreal Editor

### Steps to Reproduce

1. In GameInstance child's constructor I call the following BlueprintFunctionLibrary 
```c++
//UMyGameInstance.cpp
void UMyGameInstance::Init()
{
	Super::Init();

	USentryConfiguration::ConfigureCrashReporter();
}
//USentryConfiguration.cpp
// I attempt to use this function, yet despite my efforts to configure settings, these changes are not reflected when I observe subsequent events on Sentry.io. (But I don't think it is related to the issue that I encounter, would be great to know why I don't get those values set)
void USentryConfiguration::ConfigureCrashReporter()
{
	const TSharedPtr<FJsonObject> CrashReporterConfig = MakeShareable(new FJsonObject);

	CrashReporterConfig->SetStringField("release", "9.9.9.9");
	CrashReporterConfig->SetStringField("environment", "production");
	CrashReporterConfig->SetStringField("status", "still-in-dev");
	CrashReporterConfig->SetStringField("name", "ndsergeev");

	FString JSONConfig;
	const TSharedRef<TJsonWriter<>> JSONWriter = TJsonWriterFactory<>::Create(&JSONConfig);
	FJsonSerializer::Serialize(CrashReporterConfig.ToSharedRef(), JSONWriter);

	FGenericCrashContext::SetGameData(TEXT("__sentry"), JSONConfig);
}
```

2. Later in the execution after `BeginPlay` I intentionally crash the game
3. On Sentry.io nothing happens until I run the game again and crash it again. But at the second time I receive message from the previous run, including log file). To get the event from the second crash I will have to crash it again and so on.
4. The log that I expect to appear writes correctly from the first run, but gets delivered only after the another run with crash, the same happens with Capture Message

### Expected Result

I expected to have one crash and relatively instant update on sentry.io with that particular crash

### Actual Result

It seems like working but after the second run with crash

-- Thank you for having a look

**Comment by tustanivsky** [comment]
@ndsergeev thank you for bringing this up and providing the above details

Uploading crash reports to Sentry only after relaunching the app is an expected plugin behavior on Mac.

The thing is that `sentry-cocoa` (library that the plugin uses under the hood on macOS) provides only in-proc crash handling and writes all the relevant crash info to device storage upon app termination. On the next app launch it picks that up from there and sends the report which you can later observe at sentry.io.

Just a few more comments:
- There is no need to crash the app for the second time to get the previous crash reported - making through plugin's initialization on the next app run is enough. I assume it's just how the setup you've described above works
- `UploadSymbolsAutomatically` has nothing to do with crash reporting indeed. Essentially it's a toggle to configure the plugin's built-in tool for uploading app debug symbols to Sentry (allows to get properly symbolicated stack traces for captured events)
- `USentryConfiguration::ConfigureCrashReporter()` function sets some extra context for Unreal's default crash reporter which is an alternative mechanism for reporting crashes to Sentry while you're still relying on native integration provided with the plugin. To get those extra values included in the report please check out the `USentrySubsystem` API and use that instead.

**Comment by ndsergeev** [comment]
Amazing, thank you, Ivan (@tustanivsky).
Hope there's gonna be a way to have consistent behaviour between the platforms sometime in the future.
I will try what you have suggested. 👍🏻
