### ISSUE TITLE
Sentry Crashes Unreal when logging event or message randomly

### ISSUE THREAD

**Issue by azjata** [getsentry/sentry-unreal#458]
### Environment

How do you use Sentry?
Unreal Engine 5.3

Which version of the SDK?

0.14.0

How did you install the package? (Git-URL, Assetstore)
GITURL

Which version of Unreal?

Unreal 5.3
Windows

### Steps to Reproduce

1. Created a custom logging subsystem
2. Add key binding to create and capture event
3. Press it couple times
4. Some logs will be captured on sentry but then randomly with a next event application will crash

### Expected Result

Events should be logged and the application should not crash

### Actual Result

Events get logged couple times and then crash

### Any logs or screenshots

Function looks like following:

void USOIL_LoggingSubsystem::SentryCaptureEvent(const ESentryLevel SentryLevel, FString Text, const FString TagKey, const FString TagValue)
{
	if (IsEngineExitRequested())
		return;

	if (IsValid(SentrySubsystem))
	{
		USentryEvent* SentryEvent = NewObject<USentryEvent>();
		SentryEvent->SetLevel(SentryLevel);
		SentryEvent->SetMessage(Text);

		if (!TagKey.IsEmpty() && !TagValue.IsEmpty())
		{
			SentrySubsystem->SetTag(TagKey, TagValue);
		}

		if (IsValid(SentryEvent))
		{
			SentrySubsystem->CaptureEvent(SentryEvent);  <--- crashes over here
		}
	}
}

LoginId:154382f9473300d0ed856db5914f6d0e
EpicAccountId:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UnrealEditor_Sentry!sentry__value_from_json()
UnrealEditor_Sentry!sentry__jsonwriter_write_key()
UnrealEditor_Sentry!sentry__jsonwriter_write_value()
UnrealEditor_Sentry!sentry__jsonwriter_write_value()
UnrealEditor_Sentry!sentry__jsonwriter_write_value()
UnrealEditor_Sentry!sentry__envelope_add_event()
UnrealEditor_Sentry!sentry__prepare_event()
UnrealEditor_Sentry!sentry__capture_event()
UnrealEditor_Sentry!sentry_capture_event()
UnrealEditor_Sentry!SentrySubsystemDesktop::CaptureMessage() [D:\UnrealRepositories\SOIL_UnrealTemplate\Plugins\Sentry\Source\Sentry\Private\Desktop\SentrySubsystemDesktop.cpp:185]
UnrealEditor_Soil!USOIL_LoggingSubsystem::SentryCaptureEvent() [D:\UnrealRepositories\SOIL_UnrealTemplate\Source\Soil\SOIL_LoggingSubsystem.cpp:124]

**Comment by tustanivsky** [comment]
I believe this issue was addressed in scope of #445 which hasn't been released just yet. If you're comfortable with modifying the plugin source code please feel free to incorporate this fix manually as a temporary solution.

**Comment by azjata** [comment]
Thanks that has fixed the bug.
