### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by namnq-sipher** [getsentry/sentry-unreal#473]
What problem could Sentry solve that it doesn't?
Unreal Engine supports both x64 and arm64 Linux dedicated server but looks like Sentry only works with x64 dedicated server. Can you please update the plugin to support arm64 too?

**Comment by bitsandfoxes** [comment]
Fair request. We'll be looking into it!

**Comment by kestye** [comment]
I have the same problem and hope it gets fixed soon

**Comment by tustanivsky** [comment]
@namnq-sipher @kestye Currently to use the plugin on Linux platforms we're relying on static [sentry-native](https://github.com/getsentry/sentry-native) libs for which we currently don't have a proper mechanism allowing to build their `arm64`-compatible versions in GitHub CI environment.

However, we've been using dynamic versions of `sentry-native` libs in the past which should work for `LinuxArm64` just fine. There is a branch `support/linux-static-libs` where those are still in place so you can try it out. The corresponding plugin packages can be downloaded [here](https://github.com/getsentry/sentry-unreal/actions/runs/7205711133/artifacts/1114002965).

Please let us know whether the suggested workaround worked for you or if any other question regarding the above arise.

**Comment by slsewall** [comment]
@tustanivsky It seems that the download above is broken. Could you link a new one please?

**Comment by tustanivsky** [comment]
@slsewall Please try this [download link](https://github.com/getsentry/sentry-unreal/actions/runs/9772937883/artifacts/1662746159). Also, note the `support/linux-static-libs` branch was updated to the current `main` state

**Comment by tustanivsky** [comment]
> Unfortunately that didn't work for me, I may need to drop Sentry for now until you guys get LinuxArm support out of the box as I don't really have time to diagnose this fully and it's insane to get non LinuxArm Linux servers on gamelift for some reason.

Thanks for the update. As it was mentioned earlier building `sentry-native` libs compatible with LinuxArm64 in our CI is somewhat challenging at the moment however I'll revisit this and see what other possible options we have.

**Comment by slsewall** [comment]
> > Unfortunately that didn't work for me, I may need to drop Sentry for now until you guys get LinuxArm support out of the box as I don't really have time to diagnose this fully and it's insane to get non LinuxArm Linux servers on gamelift for some reason.
> 
> Thanks for the update. As it was mentioned earlier building `sentry-native` libs compatible with LinuxArm64 in our CI is somewhat challenging at the moment however I'll revisit this and see what other possible options we have.

Thanks that sounds great! I wish that I could just do x64 linux but unfortunately Gamelift is giving me grief on that front. If I can figure out how to make it work I'll let you know from my end as well.

**Comment by An-nym-us** [comment]
Bump For LinuxArm64 Support

**Comment by bruno-garcia** [comment]
For context, from the marketplace:

![Image](https://github.com/user-attachments/assets/0aabf7be-4e9e-41c5-8a77-5134fb195d5e)

![Image](https://github.com/user-attachments/assets/1fdc1132-30ab-40d3-a466-56e7ad0bdb86)

We're looking at the GHA hosts on Linux arm64 so we can get this going. cc @mitsuhiko

**Comment by mitsuhiko** [comment]
I added a runner. Named `ubuntu-latest-4-cores-arm64`.

**Comment by tustanivsky** [comment]
Currently, the new `ubuntu-latest-4-cores-arm64` runner, which we're using to build `sentry-native` in CI to enable arm64 support for the UE plugin, has Ubuntu 24.04. This causes some compatibility issues between the produced binaries and the Unreal itself (even with UE 5.5 Preiew 1). Can we switch the arm64-runner to use Ubuntu 22.04 ([recommended OS version](https://dev.epicgames.com/documentation/en-us/unreal-engine/linux-development-requirements-for-unreal-engine?application_version=5.5)) instead and see if it resolves the problem?
```
Current runner version: '2.320.0'
Runner name: 'ubuntu-latest-4-cores-arm64_1466ce6f6385'
Runner group name: 'Larger Runners for GDX'
Machine name: 'runner'
VM Image
  OS: Linux (arm64)
  Source: Marketplace
  Publisher: arm
  Offer: github_arm_linux_runner_2404
  Plan: github_arm_linux_runner_plan_2404
  Version: 1.0.4
```
