### ISSUE TITLE
Debug Symbols are not uploaded to Sentry from plugins downloaded from UE Marketplace

### ISSUE THREAD

**Issue by mghimirewhitehat** [getsentry/sentry-unreal#480]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
0.15.1

How did you install the package? (Git-URL, Assetstore)
UE Marketplace plugin

Which version of Unreal?
5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Mac, Windows

### Steps to Reproduce

1. Download Sentry from Marketplace
2. Open UE project and enable Sentry from Plugins
3. Enter necessary details for Sentry
4. Check Upload debug symbols automatically
5. Enter Project Name, Organization Name, Authentication token and check Upload sources
6. Click Reload 
7. I even downloaded sentry-cli from npm in windows using npm install -g @sentry/cli and from bash in Mac

### Expected Result
After packaging the game, the debug symbols should be automatically uploaded to Sentry which will displayed in Debug Files section of the project.

### Actual Result

Files are not uploaded.
![image](https://github.com/getsentry/sentry-unreal/assets/110440467/15cdaf2f-cd12-4123-bc5f-a6cc2b49d1f6)

**Comment by tustanivsky** [comment]
@mghimirewhitehat can you share some build logs? If things are set up properly you should be able to find the `Sentry: Start debug symbols upload` message there which is normally printed whenever the symbols uploading script kicks in after the game build. Subsequent output could help us understand why symbols are not uploaded to Sentry.

So far I could reproduce it neither with blueprint-only project nor C++ one with the UE Marketplace version of the plugin on my side.

**Comment by tustanivsky** [comment]
Closing it now however if the issue persists feel free to re-open.

**Comment by aaronhedquist** [comment]
I had this issue. When I tried going through sentry-cli instead, it failed telling me my sym files were > 2GB. This error is not surfaced in the output of packaging in UE.

**Comment by tustanivsky** [comment]
> I had this issue. When I tried going through sentry-cli instead, it failed telling me my sym files were > 2GB. This error is not surfaced in the output of packaging in UE.

Yes, the sym file size that `sentry-cli` can upload to Sentry is limited to 2GB. To proceed with the events symbolication when symbols are larger than that you may want to consider configuring [Symbol Server](https://docs.sentry.io/platforms/unreal/data-management/debug-files/symbol-servers/) instead.
