### ISSUE TITLE
Add support for Sentry Metrics

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-unreal#497]
So devs working in Unreal can also take adavantage of Sentry's new Metrics product, the sentry-native SDK will need to finally support Metrics as well. This is the final piece in the puzzle.

Once this is done, we should ensure Unrealy supports based on it's hybrid SDK dependencies, and update the platform SDK docs.

https://github.com/getsentry/sentry-native/issues/953

**Comment by smeubank** [comment]
moving this to backlog, since changes to the metrics product and API upstream, will return when status and prio changes

**Comment by bruno-garcia** [comment]
rip
