### ISSUE TITLE
SentryBeforeSendHandler receives empty event message when using USentrySubsystem::CaptureMessage

### ISSUE THREAD

**Issue by etelyatn** [getsentry/sentry-unreal#504]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.15.1

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.3.2

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Unreal Editor (probably others also)

### Steps to Reproduce

1. Create a MySentryBeforeSendHandler and configure it
2. Capture a message `SentrySubsystem->CaptureMessage(Message, ESentryLevel::Error);`
3. Got empty Message. For example
```cpp
USentryEvent* UMySentryBeforeSendHandler::HandleBeforeSend_Implementation(USentryEvent* Event, USentryHint* Hint)
{
	const FString& Message = Event->GetMessage();

	if (Message.IsEmpty())
	{
		FMsg::Logf(nullptr, 0, FName("LogMySentry"), ELogVerbosity::Warning, TEXT("Sentry Skipped. The message is empty"));
		return nullptr;
	}

        // Message processing

}
```

### Expected Result

Receive the message so that it can be processed in `UMytaSentryBeforeSendHandler::HandleBeforeSend_Implementation` 

### Actual Result

I'm getting an empty string.

When capturing the event, everything works as expected:
`SentrySubsystem->CaptureEvent(Event);`

**Comment by tustanivsky** [comment]
Thank you for bringing this up! I've managed to reproduce the above behavior on my end and at first glance it looks like some underlying lib issue. I'll let you know once having a solution for it.
