### ISSUE TITLE
Warning in LoadDebugSymbolsProperties

### ISSUE THREAD

**Issue by riot-pmaconi** [getsentry/sentry-unreal#526]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
0.15.1

How did you install the package? (Git-URL, Assetstore)
git

Which version of Unreal?
5.3

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Editor

### Steps to Reproduce

1. Turn off the setting to upload debug symbols automatically
2. Do not set up a sentry.properties file, since we do not want to upload debug symbols
3. Start the Unreal Editor

### Expected Result

Init proceeds normally, no warnings are logged. Ideally the parsing of the properties file only triggers if configured to upload symbols

### Actual Result
We receive this warning log:

> Sentry plugin can't find sentry.properties file

**Comment by tustanivsky** [comment]
Thank you for bringing this up! This warning definitely shouldn't appear when simply starting the editor regardless symbol uploading is enabled in project settings or not.
