### ISSUE TITLE
Update UE plugin documentation

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-unreal#55]
- [x] Highlight plugin features that are available only on certain platforms
- [x] Add explicit notice that on Mac/Windows crash capturing requires CRC setup
- [x] Add automatic breadcrumbs feature description
- [x] Update plugin initialization description
- [x] Add automatic debug symbols description
- [x] Add package to release registry ([similar to native](https://github.com/getsentry/sentry-native/blob/58cbac43ab89c803af37aa124d526be82575072d/.craft.yml#L6-L7)) so summary and link to GitHub shows up on docs.

**Comment by Edstub207** [comment]
"Add package to release registry ([similar to native](https://github.com/getsentry/sentry-native/blob/58cbac43ab89c803af37aa124d526be82575072d/.craft.yml#L6-L7)) so summary and link to GitHub shows up on docs."
- I got caught out by this I think - As before they where checked into the depot and Unreal wasn't displaying an error about the missing files initially so when I took the changes from Main (As wanted to use the automatic symbol upload) it wasn't working.

**Comment by vaind** [comment]
> I got caught out by this I think

The registry in question is sentry internal. Couldn't cause the issue you're describing. If it still persists, consider opening a new GH issue.

**Comment by Edstub207** [comment]
@vaind Previously, libraries where checked into Git which meant I could for example download main and paste into our depot (And reconcile on Perforce), to get the latest version. Now, the dependencies are part of the packaging job, which I'd missed - So getting latest requires you to download the released version (Or via the Ci Job), there isn't anything indicating how to work from Main for example.
