### ISSUE TITLE
Non-unity build failure

### ISSUE THREAD

**Issue by lederernc** [getsentry/sentry-unreal#552]
### Environment

Windows UE 5.1 using Incredibuild (non-unity builds for caching)

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

SaaS

Which version of the SDK?

0.16.0

How did you install the package? (Git-URL, Assetstore)

github

Which version of Unreal?

5.1.1 compiled from source

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?

### Steps to Reproduce

1. [Configure system to build non-unity, non-PCH](https://forums.unrealengine.com/t/how-to-compile-in-non-unity-mode/94863/3)
2. build project
3. Plugins\sentry-unreal-0.16.0-engine5.1-github\Source\SentryEditor\Private\SentrySymToolsDownloader.cpp(9): error C4668: 'ENGINE_MAJOR_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'

### Expected Result

Build should be ok.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

### Possible Solution
Add `#include "Runtime/Launch/Resources/Version.h"` to SentrySymToolsDownloader.cpp before the `ENGINE_MAJOR_VERSION` macro is used

**Comment by tustanivsky** [comment]
The fix is on its way #554

**Comment by lederernc** [comment]
> The fix is on its way #554

Thank You!
