### ISSUE TITLE
Add Support for crashes to be automatically sent to Sentry if running in -unattended mode

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#56]
What problem could Sentry solve that it doesn't?
Having sentry only work if a user is interacting with client/editor means that Automation Testing & Commandlets, potentially on remote machines will *Not* be tracked. This means some crashes will have invalid reproduction rates - An AutoTest could be constantly crashing and without manually inspecting the dump (Which might have been cleaned up) and then searching the call stack, it's difficult to know. 

it would be good to have something like a flag which says "If -unattended, always send crash to sentry" as this is a flag that will only be used during the development process. It would also be good to potentially have something like this on a project-wide setting that's configurable for certain build types/platforms, That way we can track as much of the stability as possible.  

It would also be super useful for things like running a Server on a remote machine EG: Multiplay or Playfab (Both Windows & Linux packaged builds)

**Comment by tustanivsky** [comment]
Hey @Edstub207, thank you for raising this. Currently the only option for automatic crash capturing on desktop machines (either remote or local) is using Unreal's Crash Report Client which is not an excellent solution for the scenario you've described. We're expecting Epic Games to release specific APIs with UE 5.1 for disabling the embedded crash handling mechanisms and having this kind of tool should allow Sentry to handle the whole process instead.

**Comment by tustanivsky** [comment]
@Edstub207 Is this still relevant? I believe the three latest UE versions should support automatic crash capturing out of the box. Also, a while ago we've changed `USentrySubsystem` base class to `UEngineSubsystem` so it should work just fine with automation tests too

**Comment by Edstub207** [comment]
Hi @tustanivsky I'll close this as AFAIK not a concern right now and don't have the capacity to retest at this exact moment.
