### ISSUE TITLE
Unreal Engine Debug File Uploads

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#57]
What problem could Sentry solve that it doesn't?
I'm not sure if this is possible, if it is, it might be a while away, but is it possible to have the functionality to automatically upload the debug symbols (https://docs.sentry.io/product/cli/dif/) based on what Sentry requires/expects, possibly as a "plug and play" commandlet or build graph script.

As while it's easy to do, having the functionality out of the box, with different options, such as stripping symbols and uploading for each config etc would be pretty handy at the click of a button, especially if I've built code locally and want to upload for whatever reason.  

Especially when console support becomes a thing, this will be useful for anyone using the plugin - Instead of everyone having to write a custom solution.

**Comment by tustanivsky** [comment]
Hey @Edstub207 , this is something we've been working on for a while and there is a working prototype already that allows uploading debug symbols to Sentry automatically on certain platforms when packaging the game. For Android there is even a pending PR for that (#45)

**Comment by Edstub207** [comment]
Thanks for confirming @tustanivsky, I saw the Android one - Wasn't sure about other platforms though. So it's good to know it's in the pipe for other platforms.
