### ISSUE TITLE
Expose more sentry types to Unreal or expose an delegate for listening ANR

### ISSUE THREAD

**Issue by TroutZhang** [getsentry/sentry-unreal#574]
What problem could Sentry solve that it doesn't?

Currently, if I want to filter ANR in beforesend handler, I have to use multiple if-condition together like `!Event->IsCrash()` and `Event->GetLevel() == ESentryLevel::Error` and possibly `Event->GetMessage().StartWith(TEXT("App Hanging"))` to mimic the same conditions set in https://github.com/getsentry/sentry-cocoa/blob/05896990562960d04052bf5a1548e290d89228bf/Sources/Sentry/SentryANRTrackingIntegration.m#L87-L103 

And it's not accurate due to I don't have SentryException and SentryMechanism exposed to Unreal, nothing returns me a SentryANRExceptionType with a USentryEvent pointer.

Maybe you could expose those above,  OR give another handler specifically tailored with ANR event?

**Comment by TroutZhang** [comment]
Purpose:

To have one last chance to fix a Hang app after the sentry's built-in ANR triggered, also I could add more info/text fields during the process.

**Comment by tustanivsky** [comment]
@TroutZhang Thank you for bringing this up. Just want to clarify if there are any specific platforms you need to track ANR on?

**Comment by TroutZhang** [comment]
My code was
`virtual USentryEvent* HandleBeforeSend_Implementation(USentryEvent* Event, USentryHint* Hint) override`
`{`
`	if(Event-is-ANR)`
`	{`
`		// do our code`
`	}`
`	return Super::HandleBeforeSend_Implementation(Event, Hint);`
`}`

while 
`	if(Event-is-ANR)`

is 
`	if (!Event->IsCrash() &&`
`		Event->GetLevel() == ESentryLevel::Error &&`
`		Event->GetMessage().StartsWith(TEXT("App Hanging")))`

And somehow it seems `		Event->GetMessage().StartsWith(TEXT("App Hanging")))` will not work, so I removed it now.

**Comment by TroutZhang** [comment]
@tustanivsky It's iOS for now.   Will have Android build later, may need it as well.

**Comment by tustanivsky** [comment]
Thanks for providing the extra details. We'll look into that and see what could be a convenient way to expose this to UE plugin

**Comment by tustanivsky** [comment]
@TroutZhang There's a pending PR #581 which adds `bool IsAppNotResponding() const` method to the event class to check if it's an ANR error. Note that this is an opt-in feature so you'll have to enable ANR tracking in plugin settings.

You can give it a try by downloading a corresponding plugin package from our CI [here](https://github.com/getsentry/sentry-unreal/actions/runs/9561085445/artifacts/1611811254).

**Comment by TroutZhang** [comment]
@tustanivsky  Thanks, I'm currently upgrading our project from UE5.2 to UE5.4, will try #581 after that and get back to you.
