### ISSUE TITLE
Automatic CRC configuration

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-unreal#58]
UE allows adding the PostBuildSteps section in .uplugin file where a separate shell script for CRC configuration can be called. This should allow users to skip steps described in [this guide](https://docs.sentry.io/platforms/unreal/setup-crashreport/). It's also worth considering how the CRC setup should work (via local/global config file).

**Comment by vaind** [comment]
Will this issue be relevant for the future UE v5.1?

**Comment by tustanivsky** [comment]
> Will this issue be relevant for the future UE v5.1?

Yes, CRC still will be present in UE 5.1, so having a tool that allows configuring it in a more user-friendly way should be useful
