### ISSUE TITLE
Warning is outputted with the following: crashpad WER handler module not found

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#583]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
Just before the 0.18.0 release

How did you install the package? (Git-URL, Assetstore)
Github 

Which version of Unreal?
5.4.2

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Editor commandlets

### Steps to Reproduce

1. Run a commandlet

### Expected Result
No warning is outputted

### Actual Result
The following warning is outputted: crashpad WER handler module not found

**Comment by tustanivsky** [comment]
@Edstub207 For now we've decided to simply filter out this warning since the missing WER module won't affect crash capturing by any means

**Comment by Edstub207** [comment]
Can confirm this change works for us, thanks!
