### ISSUE TITLE
IOS compile error On Unreal

### ISSUE THREAD

**Issue by cytimlin19** [getsentry/sentry-unreal#587]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
sentry-unreal-0.18.0-engine5.4-github.zip
How did you install the package? (Git-URL, Assetstore)
1. Unzip and put in the Unreal project
2. modify the project.build.cs
3. recompile project with VS

Which version of Unreal?
5.4.2 source build ( only have few small changes)

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
ok on windows and Android
but fail on IOS package

### Steps to Reproduce

1. install sentry
2. launch UE
3. Remote package IOS on Windows
5. compile error occur

### Expected Result
It should be no compile error
Maybe I miss some steps of install sentry plugin
Compile success without plugin

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?
fatal error: 'Sentry/SentrySwift.h' file not found

part of Logs:

[627/789] Compile [arm64] SentryAttachmentApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryAttachmentApple.cpp:5:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [628/789] Compile [arm64] SentryAttachment.cpp
UATHelper: Packaging (IOS):   [629/789] Compile [arm64] Module.Sentry.1.cpp
UATHelper: Packaging (IOS):   [630/789] Compile [arm64] Module.Sentry.2.cpp
UATHelper: Packaging (IOS):   [631/789] Compile [arm64] SentryBeforeSendHandler.cpp
UATHelper: Packaging (IOS):   [632/789] Compile [arm64] SPCRJointDynamicsModule.cpp
UATHelper: Packaging (IOS):   [633/789] Compile [arm64] SentryBreadcrumbApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryBreadcrumbApple.cpp:5:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [634/789] Compile [arm64] SentryConvertorsApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.cpp:3:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [635/789] Compile [arm64] SentryBreadcrumb.cpp
UATHelper: Packaging (IOS):   [636/789] Compile [arm64] SentryBreadcrumb.spec.cpp
UATHelper: Packaging (IOS):   [637/789] Compile [arm64] SentryEventApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryEventApple.cpp:5:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [638/789] Compile [arm64] SentryEvent.spec.cpp
UATHelper: Packaging (IOS):   [639/789] Compile [arm64] SentryEvent.cpp
UATHelper: Packaging (IOS):   [640/789] Compile [arm64] AnimNode_SPCRJointDynamics.cpp
UATHelper: Packaging (IOS):   [641/789] Compile [arm64] SentryFileUtils.cpp
UATHelper: Packaging (IOS):   [642/789] Compile [arm64] SentryIdApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryIdApple.cpp:5:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [643/789] Compile [arm64] SentryHint.cpp
UATHelper: Packaging (IOS):   [644/789] Compile [arm64] SentryId.cpp
UATHelper: Packaging (IOS):   [645/789] Compile [arm64] SentryLibrary.cpp
UATHelper: Packaging (IOS):   [646/789] Compile [arm64] SentryModule.cpp
UATHelper: Packaging (IOS):   [647/789] Compile [arm64] SentrySamplingContextApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentrySamplingContextApple.cpp:8:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [648/789] Compile [arm64] SentryOutputDevice.cpp
UATHelper: Packaging (IOS):   [649/789] Compile [arm64] SentryOutputDeviceError.cpp
UATHelper: Packaging (IOS):   [650/789] Compile [arm64] SentryScopeApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryScopeApple.cpp:11:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [651/789] Compile [arm64] SentrySamplingContext.cpp
UATHelper: Packaging (IOS):   [652/789] Compile [arm64] SentryScope.spec.cpp
UATHelper: Packaging (IOS):   [653/789] Compile [arm64] SentryScope.cpp
UATHelper: Packaging (IOS):   [654/789] Compile [arm64] SentrySpanApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentrySpanApple.cpp:5:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [655/789] Compile [arm64] SentrySettings.cpp
UATHelper: Packaging (IOS):   [656/789] Compile [arm64] SentrySpan.cpp
UATHelper: Packaging (IOS):   [657/789] Compile [arm64] SentrySubsystemApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentrySubsystemApple.cpp:27:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [658/789] Compile [arm64] SentryTransactionApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryTransactionApple.cpp:5:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [659/789] Compile [arm64] SentryTraceSampler.cpp
UATHelper: Packaging (IOS):   [660/789] Compile [arm64] SentrySubsystem.spec.cpp
UATHelper: Packaging (IOS):   [661/789] Compile [arm64] SentryTransaction.cpp
UATHelper: Packaging (IOS):   [662/789] Compile [arm64] SentrySubsystem.cpp
UATHelper: Packaging (IOS):   [663/789] Compile [arm64] SentryTransactionContextApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryTransactionContextApple.cpp:5:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [664/789] Compile [arm64] SentryUserApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryUserApple.cpp:5:
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Infrastructure\SentryConvertorsApple.h:7:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [665/789] Compile [arm64] SentryTransactionContext.cpp
UATHelper: Packaging (IOS):   [666/789] Compile [arm64] SentryUserFeedbackApple.cpp
UATHelper: Packaging (IOS):   In file included from C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\SentryUserFeedbackApple.cpp:8:
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: fatal error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   #import <Sentry/SentrySwift.h>
UATHelper: Packaging (IOS):           ^~~~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (IOS):   C:\case\<project>\Plugins\Sentry\Source\Sentry\Private\Apple\Convenience\SentryInclude.h:14:9: note: did not find header 'SentrySwift.h' in framework 'Sentry' (loaded from '/Users/<user>/UE5/Builds/<user>/D/case/project/UE5Engine/Engine/Intermediate/UnzippedFrameworks/Sentry/Sentry.embeddedframework')
UATHelper: Packaging (IOS):   1 error generated.
PackagingResults: Error: 'Sentry/SentrySwift.h' file not found
UATHelper: Packaging (IOS):   [667/789] Compile [arm64] SentryUser.spec.cpp
UATHelper: Packaging (IOS):   [668/789] Compile [arm64] SentryUser.cpp
UATHelper: Packaging (IOS):   [669/789] Compile [arm64] SentryUserFeedback.cpp

**Comment by tustanivsky** [comment]
@cytimlin19 Thanks for raising this, we'll check it out and get back to you.

**Comment by cytimlin19** [comment]
Add a note here.
I was using sentry-unreal-0.16.0-engine5.3-github.zip on UE5.3.1 (source build).
And remote IOS build didn't give me this compile error.

**Comment by tustanivsky** [comment]
@cytimlin19 Thanks for the heads up, we're looking into that and currently it seems that one of the most recent plugin's dependencies update has caused these errors.

**Comment by tustanivsky** [comment]
@cytimlin19 I've managed to configure iOS remote build on my side and package our sample project successfully without any compilation errors (tested with UE 5.2/5.4, binary distribution).

Can you confirm that `<ProjectRoot>\Plugins\Sentry\Source\ThirdParty\IOS\Sentry.framework\PrivateHeaders` contains `SentrySwift.h` header in it so that we can be sure nothing is wrong with the plugin archive we have on GitHub?

Also, I've noticed some issues with incorrect includes when building the project on Mac (#591) but I don't think that these were relevant.
