### ISSUE TITLE
Crash when re-initializing the sentry subsystem

### ISSUE THREAD

**Issue by diekleinekuh** [getsentry/sentry-unreal#592]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
Git-URL, 18.0 git hub release for unreal 5.3

Which version of Unreal?
Unreal 5.3.2

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
We only use sentry for the windows game target for now.

### Steps to Reproduce

1. Initialize the sentry subsystem with a call to InitWithSettings, Initialize or setting InitAutomatically in USentrySettings to true
2. Initialize the sentry subsystem again later when having more data by calling InitWithSettings or Initialize again without calling Deinitialize first
3. Wait for a log message to be printed by unreal

### Expected Result

The app should not crash.

### Actual Result

The app crashes

### Any logs or screenshots

The reason for the crash is that when calling Initialize multiple times the  `FSentryOutputDevice` instance in OutputDevice gets destroyed without deregistering them first from GLog (see [USentrySubsystem::ConfigureOutputDevice()](https://github.com/getsentry/sentry-unreal/blob/e68c009748a587420a9f111e2bd077bc70f75740/plugin-dev/Source/Sentry/Private/SentrySubsystem.cpp#L642) ). 

Similar problems might be in `USentrySubsystem::ConfigureOutputDeviceError()` as the old FSentryOutputDeviceError device is still in GError when it is torn down while being used at the same time as the parent for the newly created device.

**Comment by bitsandfoxes** [comment]
Sorry about that, the SDK should definitely not cause a crash.
Initializing the SDK twice is not really an intended or even recommended approach. What is it that you cannot provide during the original init? Maybe there is a way to set this later on.

**Comment by diekleinekuh** [comment]
Hi,
thanks for reacting so quickly. I'm setting "Environment" to "production" or "staging" depending on some config file. I guess I could make it available earlier but I cannot hard code it. Currently I'm doing this in `GameInstance::Init` but having this as early as possible would be preferrable obviously. 

Those are the docs I'm following when settings the environemnt.
https://docs.sentry.io/platforms/unreal/configuration/environments/

At the moment I disabled automatic initialization as a workaround. I guess I could also not use `InitializeWithSettings` and modify the settings myself even before the automatic initialization kicks in ...

**Comment by tustanivsky** [comment]
@diekleinekuh You should be able to fix this by calling a Sentry subsystem's 'Close' method before re-initializing it with new the config values. Basically, it takes care of deregistering our custom output devices which apparently are the reason for those crashes described above.

**Comment by tustanivsky** [comment]
@tustanivsky While you can still rely on the workaround suggested above it's a fair request to handle Sentry re-initialization in way that the plugin doesn't crash. I've made corresponding changes in #594 so the fix should be available in the next plugin release.

**Comment by bitsandfoxes** [comment]
Thanks for taking care of the reinitialization @tustanivsky!
