### ISSUE TITLE
Setting a custom user id doesn't work

### ISSUE THREAD

**Issue by diekleinekuh** [getsentry/sentry-unreal#593]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?

How did you install the package?
https://github.com/getsentry/sentry-unreal/releases/download/0.18.0/sentry-unreal-0.18.0-engine5.3-github.zip

Which version of Unreal?
5.3.2

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Windows Game build in Test config

### Steps to Reproduce
1. Use automatic SDK initialization
2. Put this code into a custom game instance
```c++
void UMyGameInstance::Init()
{
	if (USentrySubsystem* SentrySubsystem = GEngine->GetEngineSubsystem< USentrySubsystem>())
	{
		FString MyCustomGuid = TEXT("something-random");
		USentryUser* User = NewObject<USentryUser>();
		User->SetId(MyCustomGuid);
		User->SetUsername(TEXT("myusername"));
		TMap<FString, FString> ExtraData;
		ExtraData.Add(TEXT("MyCustomId"), MyCustomGuid);
		User->SetData(ExtraData);
		SentrySubsystem->SetUser(User);
	}
	Super::Init()
}
``` 
3. Compile the app and upload stripped debug info
4. Crash the app
5. observe the crash report in sentry

### Expected Result

Seeing an event on sentry.io having `user.id`="something-random"

### Actual Result

I'm seeing an event on sentry.io that has a different `user.id`. It seems to be set to the same value as the `login_id` field of the unreal context where the crash report is written to. But I can see the `MyCustomId` field in `ExtraData` being set to "something-random" and I can also see my "myusername" being present in the event on sentry.

**Comment by tustanivsky** [comment]
@diekleinekuh I've experimented with this a bit on my end and figured out that this issue occurs only when using the default `Crash Reporter` tool for crash capturing instead of the plugin's native integration. Currently it looks like Sentry processes such event reports differently and at some point `user.id` gets overwritten by Unreal's `login_id` value. I'll keep looking into that and let you know if anything new comes up.

**Comment by tustanivsky** [comment]
> @tustanivsky So if I'm setting `EnableAutoCrashCapturing=true` it would work? I had that on my list of things to check out anyway.

Yes, it will allow you to switch the default UE crash capturing mechanism to Sentry's and in this case `user.id` value should be the one you've set as in example above.

**Comment by diekleinekuh** [comment]
I can confirm that switching to Sentry's crash capturing mechanism by setting `EnableAutoCrashCapturing=true` makes the `user.id` show up as desired. For now this is fine for me. I don't really miss the epic crash reporter.

**Comment by tustanivsky** [comment]
Thanks for the update, I'm closing this for now since after some research the original issue doesn't relate to UE plugin itself but rather to how Sentry processes CRC reports on the server side.

**Comment by tustanivsky** [comment]
Alright, we've managed to [confirm](merge_unreal_user_info) that the User ID overwriting happens on a server side of things and has nothing to do with plugin itself.
