### ISSUE TITLE
Automatic Sentry CLI update in CI

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-unreal#60]
In order to automate debug symbols upload for certain platforms Sentry CLI was added to the plugin. To keep this tool up to date existing CI workflow for plugin dependencies can be extended.

**Comment by bruno-garcia** [comment]
It's important to gracefully downgrade if Sentry is offline: 
* https://github.com/getsentry/team-mobile/issues/3

Also checking in the binaries is suboptimal, makes the case to split the repo we work on and what we tag and make available to customers
