### ISSUE TITLE
Non-ascii characters in event messages

### ISSUE THREAD

**Issue by andreybond611** [getsentry/sentry-unreal#621]
Hello.

Is/will there be support for non-ascii characters in sent messages on desktop?

Right now 'sentry_value_new_message_event' takes const char* and
when 'SentrySubsystemDesktop::CaptureMessage()' called, FString parameter converts to basic string and loses everything non-english.
It would be helpful when we capture user feedback for example.

**Comment by tustanivsky** [comment]
Hey @andreybond611, thank you for bringing this up. While supporting non-ASCII characters seems technically possible, we'll need to investigate further to confirm. I'll keep you updated on our findings.
