### ISSUE TITLE
Server vs Client

### ISSUE THREAD

**Issue by d11ahirst** [getsentry/sentry-unreal#623]
What is the best way to configure sentry for an unreal server/client is it to use the same DSN etc or have seperate projects with different DSN's?

If the latter is the case how does the wizard handle more than 1 DSN?

Thanks

**Comment by tustanivsky** [comment]
Hey @d11ahirst, having a single Sentry project for both server and client should be sufficient. Events captured for each build target will have a corresponding tag so you can easily filter them if needed.
