### ISSUE TITLE
Sentry does not work on dedicated server based on Amazon_Linux_2023 and Amazon_Linux_2

### ISSUE THREAD

**Issue by VARGDevelopment** [getsentry/sentry-unreal#635]
### Environment
Amazon_Linux_2023 and Amazon_Linux_2

### How do you use Sentry?
Just start dedicated server on AWS instance.

### Which version of the SDK?
SENTRY_SDK_VERSION "0.7.6"

### How did you install the package? (Git-URL, Assetstore)
Git-URL(Not-marketplace)

### Which version of Unreal?
5.3

### Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
All good. Works perfect on Windows.

### Steps to Reproduce

1. Build Dedicated server and upload to AWS
2. Start server

### Expected Result

Sentry works and initializes fine. 

### Actual Result
Sentry fails to initialize
![Image](https://github.com/user-attachments/assets/c66b9c17-99d1-40ab-b1a2-43e4297657ab)

What I found out that - 
```
ldd crashpad_handle give us:
libc++.so.1 => not found
libc++abi.so.1 => not found
```

**Comment by tustanivsky** [comment]
Hey @VARGDevelopment, please try `sudo apt-get install libc++-dev libc++abi-dev libcurl-dev` on your server to install these missing Crashpad dependencies.

**Comment by VARGDevelopment** [comment]
> Hey [@VARGDevelopment](https://github.com/VARGDevelopment), please try `sudo apt-get install libc++-dev libc++abi-dev libcurl-dev` on your server to install these missing Crashpad dependencies.

![Image](https://github.com/user-attachments/assets/7445f06d-9e3b-4421-9935-92dd844d6c6a)
Unfortunately does not work. Im not Linux user from start.

**Comment by tustanivsky** [comment]
The dependencies listed above are required to start the Crashpad on Linux. Since `libc++` is part of the LLVM project you can try installing these missing packages by following this [guide](https://apt.llvm.org/).

**Comment by VARGDevelopment** [comment]
@tustanivsky installed LLVM and got the same problem. Maybe crashpad could be build statically for that case?

**Comment by tustanivsky** [comment]
> [@tustanivsky](https://github.com/tustanivsky) installed LLVM and got the same problem. Maybe crashpad could be build statically for that case?

@VARGDevelopment Currently there's no way to link crashpad statically. However we have an experimental branch in this repo where the plugin's Linux dependencies are built as shared lib which technically could help you to resolve the aforementioned portability issue with AL2 virtual machines. You can try to download package from our GitHub CI [here](https://github.com/getsentry/sentry-unreal/actions/runs/10935786751/artifacts/1951596230).

**Comment by MaxRavitsky** [comment]
Got latest release from [here ](https://github.com/getsentry/sentry-unreal/releases) and the same problem occured
