### ISSUE TITLE
Installation issues on UE 5.4

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unreal#644]
Reported here: https://www.unrealengine.com/marketplace/en-US/product/sentry-01/reviews

> could not install to UE5.4, but can install to UE5.3 and UE5.2,
> By RealmDelight on June 18, 2024 4:17 PM - Edited on June 18, 2024 6:13 PM

@bitsandfoxes should we get these reviews by email somehow?

**Comment by bruno-garcia** [comment]
Is there a way to test the package after upload, so we can at least be aware immediately as opposed to waiting for customer feedback?

Or/and other ways to improve this?

**Comment by tustanivsky** [comment]
The UE Marketplace installation was fixed with the latest update.
