### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by PlasmaDev5** [getsentry/sentry-unreal#652]
### Environment

How do you use Sentry?

This error was encounter when trying to build the source in windows 11

Which version of the SDK?

This github repo

Which version of Unreal?

5.4 but not even at that stage yet

### Steps to Reproduce

1. Run init-win.ps1
2. Hit issue

### Expected Result

Build script runs without errors

### Actual Result

The build script ran into an error
"The input name "conclusion" cannot be resolved to a property."

### Any logs or screenshots

![Image](https://github.com/user-attachments/assets/90bb6a1e-1a0a-4997-9216-db805509a6aa)

**Comment by tustanivsky** [comment]
It looks like an issue with the PowerShell environment. Please try printing `$PSVersionTable` built-in variable to check which PS version you're using. If it's `5.X` upgrading to a newer [Power Shell](https://github.com/powershell/powershell) can help to resolve the above error.

**Comment by PlasmaDev5** [comment]
Turns out that powershell installed alongside the old version and defaulted to the wrong one. I have now run the script without issues.
That said i am now getting errors running the sample project on Unreal 5.4 

`1>D:\Sentry\Unreal\SDK\sentry-unreal\sample\Plugins\sentry\Source\Sentry\Private\Desktop\Convenience\SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory
1>[2/27] Compile [x64] SentryEventDesktop.cpp
1>D:\Sentry\Unreal\SDK\sentry-unreal\sample\Plugins\sentry\Source\Sentry\Private\Desktop\Convenience\SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory
1>[3/27] Compile [x64] SentryIdDesktop.cpp
1>D:\Sentry\Unreal\SDK\sentry-unreal\sample\Plugins\sentry\Source\Sentry\Private\Desktop\Convenience\SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory
1>[4/27] Compile [x64] SentryConvertorsDesktop.cpp
1>D:\Sentry\Unreal\SDK\sentry-unreal\sample\Plugins\sentry\Source\Sentry\Private\Desktop\Convenience\SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory
1>[5/27] Compile [x64] SentryEvent.cpp
1>D:\Sentry\Unreal\SDK\sentry-unreal\sample\Plugins\sentry\Source\Sentry\Private\Desktop\Convenience\SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory
1>[6/27] Compile [x64] SentryId.cpp
1>D:\Sentry\Unreal\SDK\sentry-unreal\sample\Plugins\sentry\Source\Sentry\Private\Desktop\Convenience\SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory`

**Comment by tustanivsky** [comment]
Running the `init-win.ps1` script should handle downloading the required dependencies from GitHub CI and creating a symlink to plugin dir in `<repo-root>\sample\Plugins`. Once these steps are completed the sample project has to be ready for testing things out.

Can you check if the `Win64` dir exists in `<repo-root>\sample\Plugins\sentry\Source\ThirdParty` and it contains all the required headers/binaries for `sentry-native` which plugin uses under the hood?

**Comment by PlasmaDev5** [comment]
ThirdParty only contains a CLI folder. this looks to only contain platform executables for example sentry-cli-Windows-x86_64.exe

**Comment by tustanivsky** [comment]
> ThirdParty only contains a CLI folder. this looks to only contain platform executables for example sentry-cli-Windows-x86_64.exe

Apparently, the initialization script failed to download pre-build dependencies from our CI, so you're facing those build errors. Can you re-run it and share the output logs? Normally it should look something like this:
```
~ ./init-win.ps1
Creating a link (directory junction) from D:\unreal-projects\sentry-unreal/sample/Plugins/sentry to D:\unreal-projects\sentry-unreal\plugin-dev
Downloading native SDKs from the latest CI pipeline
Looking for the latest successful CI run on branch 'main'
  ... found CI run ID: 11274849111
Downloading Android SDK to D:\unreal-projects\sentry-unreal\plugin-dev\Source/ThirdParty/Android ...
Downloading IOS SDK to D:\unreal-projects\sentry-unreal\plugin-dev\Source/ThirdParty/IOS ...
Downloading Linux SDK to D:\unreal-projects\sentry-unreal\plugin-dev\Source/ThirdParty/Linux ...
Downloading Mac SDK to D:\unreal-projects\sentry-unreal\plugin-dev\Source/ThirdParty/Mac ...
Downloading Win64-Crashpad SDK to D:\unreal-projects\sentry-unreal\plugin-dev\Source/ThirdParty/Win64/Crashpad ...
Downloading Win64-Breakpad SDK to D:\unreal-projects\sentry-unreal\plugin-dev\Source/ThirdParty/Win64/Breakpad ...
Downloading D:\unreal-projects\sentry-unreal\scripts/../plugin-dev/Source/ThirdParty/CLI/sentry-cli-Darwin-universal
Downloading D:\unreal-projects\sentry-unreal\scripts/../plugin-dev/Source/ThirdParty/CLI/sentry-cli-Linux-x86_64
Downloading D:\unreal-projects\sentry-unreal\scripts/../plugin-dev/Source/ThirdParty/CLI/sentry-cli-Windows-x86_64.exe
```
