### ISSUE TITLE
Debug symbol upload for Android fails with Gradle (works with CLI, and on desktop (Windows) build)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unreal#666]
[From Discord](https://discord.com/channels/621778831602221064/1211958154984820776/1299820400620077138)

OS: Windows
Build: Android build with Gradle

Sentry can`t automatically upload debug symbols for Android, but it automatically uploads symbols for Windows builds. The Android building process returns an error: Invalid org token (HTTP status 401). However, I can manually upload debug symbols for Android using the console sentry CLI. I used the same token for automatic Windows debug symbol upload and for manually uploading debug symbols for Android using the CLI.
I have added screenshots with errors, corrected upload debug symbols for Windows, and manually uploaded symbols for Android.

![Image](https://github.com/user-attachments/assets/eb33d5c9-8389-44ed-bb45-78cd8cc0d74e)

![Image](https://github.com/user-attachments/assets/3029efac-a43a-48d4-849c-182ce300a224)
![Image](https://github.com/user-attachments/assets/b2baefa2-d269-4f58-9719-a60658705eaf)

Task failed `uploadSentryProguardWMappingsRelease`

**Comment by bruno-garcia** [comment]
The error message is "Invalid org token` so I suspect gradle is picking up a token from somewhere like env var (`SENTRY_AUTH_TOKEN`) or `sentry.properties`.

The error message comes from here: https://github.com/getsentry/sentry-cli/blob/6d0729dafaf0ce928fcb591f4c701a051c98ddf4/src/commands/login.rs#L76-L91

So does this mean Sentry rejected the token or the format of the token is invalid? (Or could be either?)

**Comment by Rostislav98** [comment]
I have "sentry.properties" in my project folder, but they were generated by Sentry Unreal pugin, when I set up token, project name, organization name in plugin engine settings. When I changed vales its regenerated in folder. The values the same like in plugin engine settings.

After my builds on Android fails,  i used senty CLI for uploading android debug symbols. And they saved my valid token somewhere in PC, when i first log in. But, after that, I tryied upload adnroid debug symbols automaticaly. and got error again. I do not see SENTRY_AUTH_TOKEN in enviroment vairables on my PC.

**Comment by tustanivsky** [comment]
@Rostislav98 Which UE plugin version do you have? How do you use Sentry - SaaS / self-hosted?

It looks similar to #502.

The Sentry Android Gradle plugin which's used in Unreal for symbol upload also had this issue (https://github.com/getsentry/sentry-android-gradle-plugin/issues/694) so we've upgraded it recently to get a corresponding fix (#633) and make things work out of the box. It should be available starting from `0.20.0`.

**Comment by tustanivsky** [comment]
Updating plugin resolved the symbol upload issue.
