### ISSUE TITLE
Sentry plugin 0.20.1 implementation in Unreal Engine 4.27.2 Visual Studio compile error

### ISSUE THREAD

**Issue by gianluca-manca** [getsentry/sentry-unreal#691]
### Environment

I am using Sentry IO in an Unreal Engine project

Which version of the SDK?
0.20.1
Unreal Engine version 4.27.2 Custom
It is happening in Visual Studio 2019, after regenerating the solution file and trying to build the solution

### Steps to Reproduce
1. Add the latest Sentry IO plugin to the plugin folder and enable it in Unreal Engine
2. Regenerate the Visual Studio Solution file
3. Try to compile the project

### Expected Result
The build of the solution is successful

### Actual Result
The build failed 

### Any logs or screenshots
D:\Workspaces\MyProject\Plugins\ApplicationCore\SourceEditorEditor.Build.cs : warning : Referenced directory 'D:\Workspaces\MyProject\Plugins\Source\Settings' does not exist.
1>D:\Workspaces\MyProject\Plugins\ConfigurationCore\Source\ConfigurationCoreEditor.Build.cs : warning : Referenced directory 'D:\Workspaces\UnrealEngine\Engine\Source\Public' does not exist.
1>D:\Workspaces\MyProject\Plugins\Source.Build.cs : warning : Referenced directory 'D:\Workspaces\MyProject\Plugins\Source\Settings' does not exist.
1>D:\Workspaces\MyProject\Plugins\Rendering\Source\RenderingEditor.Build.cs : warning : Referenced directory 'D:\Workspaces\MyProject\Plugins\Source\Settings' does not exist.
1>UnrealBuildTool : error : Unable to instantiate module 'Sentry': System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Workspaces\MyProject\Plugins\SentryIO\Source\Sentry\../ThirdParty\Win64\bin\sentry.dll'.
1>                           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>                           at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
1>                           at Sentry.CopyPluginBinary(String SourceFile, String DestFile, String DestFolder) in d:\Workspaces\MyProject\Plugins\SentryIO\Source\Sentry\Sentry.Build.cs:line 204
1>                           at Sentry.LoadThirdPartyLibrary(String libname, ReadOnlyTargetRules Target) in d:\Workspaces\MyProject\Plugins\SentryIO\Source\Sentry\Sentry.Build.cs:line 163
1>                           at Sentry..ctor(ReadOnlyTargetRules Target) in d:\Workspaces\MyProject\Plugins\SentryIO\Source\Sentry\Sentry.Build.cs:line 98
1>                        (referenced via default plugins -> Sentry.uplugin)

**Comment by tustanivsky** [comment]
Hey @gianluca-manca, how exactly did you integrate the plugin? Did you download it from the release page?

According to the above error log it looks like you've copied the `plugin-dev` folder from this repo root to your project's `Plugins` dir. If so, the version in the repo is not self-contained and requires additional configuration (see [CONTRIBUTING.md](https://github.com/getsentry/sentry-unreal/blob/main/CONTRIBUTING.md) for details)

**Comment by gianluca-manca** [comment]
Hi @tustanivsky , thanks for the answer, I didn't noticed that, I used the version 0.5.0 before the latest and didn't needed this step.
Now that I run that script, I then copied the content inside the plugin-dev folder into the plugin folder of the project and I got this

D:\Workspaces\MyProject\Plugins\SentryIO\Source\Sentry\Private\Desktop\Convenience/SentryInclude.h(9): fatal error C1083: Cannot open include file: 'sentry.h': No such file or directory

Did I miss any additional step?
Thanks

**Comment by tustanivsky** [comment]
Can you confirm that after running the script and copying the downloaded artifacts to your project there's a `SentryInclude.h` file in `<YourProjectRoot>/Plugins/Sentry/Source/ThirdParty/Win64/Crashpad/include` directory?

If it's there then doing a rebuild might help, just make sure you've removed `Binaries`, `Build`, `Intermediate` and `Saved` folders both in the project and plugin dirs.

**Comment by gianluca-manca** [comment]
No, there is nothing inside that folder except for the CLI folder.
This the output of the init-win.ps1

`PS C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts> .\init-win.ps1
The variable '$IsWindows' cannot be retrieved because it has not been set.
At C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts\init-win.ps1:3 char:10                                        + if (-not $IsWindows)                                                                                                  +          ~~~~~~~~~~                                                                                                       + CategoryInfo          : InvalidOperation: (IsWindows:String) [], RuntimeException                                     + FullyQualifiedErrorId : VariableIsUndefined

Link C:\Users\user\Downloads\sentry-unreal-0.20.1/sample/Plugins/sentry already exists and matches target C:\Users\user\Downloads\sentry-unreal-0.20.1\plugin-dev - skipping
Downloading native SDKs from the latest CI pipeline
fatal: not a git repository (or any of the parent directories): .git
Looking for the latest successful CI run on branch ''
gh : The term 'gh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts\download-sdks.ps1:8 char:11
+     $id = gh run list --branch $branch --workflow package-plugin-work ...
+           ~~
    + CategoryInfo          : ObjectNotFound: (gh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING:   ... no successful CI run found on
Looking for the latest successful CI run on branch 'main'
gh : The term 'gh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts\download-sdks.ps1:8 char:11
+     $id = gh run list --branch $branch --workflow package-plugin-work ...
+           ~~
    + CategoryInfo          : ObjectNotFound: (gh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING:   ... no successful CI run found on main
fatal: not a git repository (or any of the parent directories): .git
Downloading C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts/../plugin-dev/Source/ThirdParty/CLI/sentry-cli-Darwin-universal
Downloading C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts/../plugin-dev/Source/ThirdParty/CLI/sentry-cli-Linux-x86_64
Downloading C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts/../plugin-dev/Source/ThirdParty/CLI/sentry-cli-Windows-x86_64.exe
PS C:\Users\user\Downloads\sentry-unreal-0.20.1\scripts>`

**Comment by tustanivsky** [comment]
Than you for letting us know that the issue is resolved!

Just a few things to add here for extra context:

- Based on your latest output log it seems that you've downloaded the repo as zip archive from GitHub rather than cloned it. Basically, it may prevent the script from detecting which version of the plugin dependencies have to be downloaded.
- GitHub CLI tool must be installed and added to PATH in order to make script working properly.
- There's something odd with the PowerShell installation. You can try printing `$PSVersionTable` built-in variable to check which PS version you're using. If it's `5.X` upgrading to a newer [Power Shell](https://github.com/powershell/powershell) can help to resolve some the above errors.

**Comment by gianluca-manca** [comment]
Yes, I downloaded the zip file, my bad. I think that was the main problem.
Thanks again!
