### ISSUE TITLE
USentrySubsystem::StartSession() crashes games on the Android platform

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-unreal#694]
### Environment

**How do you use Sentry?**
Sentry SaaS (sentry.io)

**Which version of the SDK?**
0.21.0

**How did you install the package? (Git-URL, Assetstore)**
Using the crash reporter

**Which version of Unreal?**
5.3

### Problem

The calling of the method `USentrySubsystem::StartSession()` crashes games on the Android platform. 

Under the hood it calls `SentrySubsystemAndroid::StartSession`, which calls `SentryBridgeJava::startSession`. However,  `io.sentry.unreal.SentryBridgeJava` defined [here](https://github.com/getsentry/sentry-unreal/blob/0.21.0/plugin-dev/Source/Sentry/Private/Android/Java/SentryBridgeJava.java) doesn't have such a method. 

As a result this check fails:
```
checkf(Method.Method, TEXT("Unable to find Java Method %s with Signature %s"), UTF8_TO_TCHAR(MethodName), UTF8_TO_TCHAR(FunctionSignature));
```
in method `FSentryJavaObjectWrapper::GetStaticMethod`.

`USentrySubsystem::StartSession` is being called after application started inside `AGameMode::StartPlay`.

The reason is the same method is being called from here:
https://github.com/getsentry/sentry-unreal/blob/0.21.0/plugin-dev/Source/Sentry/Private/Android/SentrySubsystemAndroid.cpp#L257

But as stated, there is no definition of the method in code here:
https://github.com/getsentry/sentry-unreal/blob/0.21.0/plugin-dev/Source/Sentry/Private/Android/Java/SentryBridgeJava.java

**Comment by tustanivsky** [comment]
@InterstellarStella Thank you for bringing it up. This issue was addressed in #696 and the corresponding fix will be available in the next UE plugin release.
