### ISSUE TITLE
Error Launching Project in Editor

### ISSUE THREAD

**Issue by sapaczb** [getsentry/sentry-unreal#7]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
sentry.io

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
sentry-unreal "VersionName": "0.0.1"

Unreal Engine Version:
4.27.2

### Steps to Reproduce
1. Clone repo into project plugins folder (/Project/Plugins/)
2. Generate VS project files (right-click .uproject)
3. Open solution, compile, debug.

### Expected Result
Unreal Editor would open

### Actual Result
Critical error 
[CallStack.txt](https://github.com/getsentry/sentry-unreal/files/8610840/CallStack.txt)

**Comment by tustanivsky** [comment]
Hey @sapaczb, please pull the latest plugin version and try once again. I believe this [commit](https://github.com/getsentry/sentry-unreal/commit/317aa2fc69b77f007b1cb404330f32a02f1845f7) should fix the issue with launching the editor.

**Comment by sapaczb** [comment]
Awesome, the fix worked. Thanks @tustanivsky
