### ISSUE TITLE
Weird event captured: `<unlabeled event>`

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unreal#71]
See https://sentry.io/organizations/sentry-sdks/issues/3216058856/?project=6253052

When is it captured? Maybe from the editor?

**Comment by tustanivsky** [comment]
> See https://sentry.io/organizations/sentry-sdks/issues/3216058856/?project=6253052
> 
> When is it captured? Maybe from the editor?

I've generated a similar event when running tests in the editor. It's odd though that there is no message attached. I'll take a closer look at this

**Comment by tustanivsky** [comment]
The issue was caused by a faulty test which was removed a while ago, closing it now.
