### ISSUE TITLE
Event capturing stopped working on Mac

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-unreal#74]
### Environment

Which version of Unreal?

UE 4.27, Mac OS

### Steps to Reproduce

1. Download the latest plugin version and it's dependencies using `init.sh` script
2. Launch `PlaygroundSentry` project from `sample` folder
3. Start `SentryDemo` scene

### Expected Result

Events are captured normally and displayed in the Sentry dashboard.

### Actual Result

When trying to run the demo scene in the editor it hangs infinitely.
In packaged build demo runs without issues however events aren't captured.

**Comment by tustanivsky** [comment]
@vaind I did a quick research and found out that this issue appeared after binaries were removed from the repo. Apparently, there is something with the libraries we’re downloading from GitHub. I wasn’t able to collect any logs or debug anything, so that’s my only guess at the moment

Also, few more things I’ve discovered:
- after replacing downloaded binaries with those that were in the repo previously everything starts working again
- there is no such issue on Windows

**Comment by tustanivsky** [comment]
UPD: It turned out that this is a permission-related issue. After running these commands everything works on Mac without problems:

`$ chmod +x crashpad_handler`
`$ chmod +x libsentry.dylib`

@vaind should we add those to [build-mac.sh](https://github.com/getsentry/sentry-unreal/blob/main/scripts/build-mac.sh)?

**Comment by vaind** [comment]
`chmod +x libsentry.dylib` makes no sense to me - are you sure that's necessary? We don't execute that file

As for the `crashpad_handler`, yeah, if needed we should do it but I don't think we do in sentry-unity so what gives? 🤔 

Also we should add `chmod +x` to the mac/linux debug-symbol upload script

**Comment by tustanivsky** [comment]
> `chmod +x libsentry.dylib` makes no sense to me - are you sure that's necessary? We don't execute that file
 Yes, you're right - we don't need to change permission for `libsentry.dylib`. I've managed to confirm that modifying `crashpad_handler` is enough after removing all of the files cached earlier
