### ISSUE TITLE
Powershell Script isn't digitially signed, 

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#83]
### Environment

How do you use Sentry?
Sentry.io

Which version of the SDK?
Latest 

How did you install the package? (Git-URL, Assetstore)
Downloaded from Github manually (And then manually integrated the dependencies from the release pipeline)

Which version of Unreal?
Unreal 5.0.0 

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Editor. 

### Steps to Reproduce

1. Compile the editor 

### Expected Result
The script works out of the box. 

### Actual Result

** For PROJECTEditor-Win64-Development **
[1/1] Executing post-build script (PostBuild-1.bat) (0:00.42 at +0:00)
File C:\Workspaces\PROJECT\PROJECT\Plugins\External\SentryUnrealPlugin\Scripts\upload-debug-symbols-win.ps1
cannot be loaded. The file
C:\Workspaces\PROJECT\PROJECT\Plugins\External\SentryUnrealPlugin\Scripts\upload-debug-symbols-win.ps1 is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess

Error executing C:\Windows\system32\cmd.exe (tool returned code: 1)

**Comment by Edstub207** [comment]
Update:  Apparently this might not be possible unless set by a group policy. Is there an alternative script that could be run instead to upload that doesn't require changes like this?

https://www.sqlshack.com/choosing-and-setting-a-powershell-execution-policy/

**Comment by tustanivsky** [comment]
> Update: Apparently this might not be possible unless set by a group policy. Is there an alternative script that could be run instead to upload that doesn't require changes like this?
> 
> https://www.sqlshack.com/choosing-and-setting-a-powershell-execution-policy/

Currently plugin doesn't provide any other scripts for the debug symbols upload. I think the only options to try for now are the following:

- Change execution policy in `Sentry.uplugin` post build steps section
- Use Sentry CLI tool that is distributed along with the plugin (`plugin-dev/Source/ThirdParty/CLI`) directly in order to upload symbols, though some extra scripting will be required in this case

**Comment by Edstub207** [comment]
> > Update: Apparently this might not be possible unless set by a group policy. Is there an alternative script that could be run instead to upload that doesn't require changes like this?
> > https://www.sqlshack.com/choosing-and-setting-a-powershell-execution-policy/
> 
> Currently plugin doesn't provide any other scripts for the debug symbols upload. I think the only options to try for now are the following:
> 
> * Change execution policy in `Sentry.uplugin` post build steps section
> * Use Sentry CLI tool that is distributed along with the plugin (`plugin-dev/Source/ThirdParty/CLI`) directly in order to upload symbols, though some extra scripting will be required in this case

Yeah I spotted that the execution policy was set in that post build step after trying to change it locally and it not working. Changing the UProject file worked

**Comment by tustanivsky** [comment]
> Changing the UProject file worked

Just wanted to clarify - did you mean `Sentry.uplugin` here? Also, which policy type did you specify?

**Comment by Edstub207** [comment]
Yes, that's correct. 
			"powershell -ExecutionPolicy bypass -File $(PluginDir)/Scripts/upload-debug-symbols-win.ps1 $(TargetPlatform) $(TargetName) $(TargetType) $(ProjectDir) $(PluginDir)"

**Comment by vaind** [comment]
0ab1640cff6a0809a59076637eb59ccf3d79b412 changed exectuion policity to `Bypass` which should resolve this issue.
