### ISSUE TITLE
(iOS) Error uploading packaged project to App Store

### ISSUE THREAD

**Issue by sapaczb** [getsentry/sentry-unreal#9]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
"Version": "0.0.1"

### Steps to Reproduce
1. Add sentry-unreal to Unreal project
2. Package Project (Shipping)
3. Upload to App Store via Transporter

### Expected Result
App successfully uploads

### Actual Result
Error uploading:
ERROR ITMS-90087: "Unsupported Architectures. The executable for MyGame.app/Frameworks/Sentry.framework contains unsupported architectures '[x86_64, i386]'."

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

**Comment by tustanivsky** [comment]
Hey @sapaczb, please pull the latest plugin version ([commit](https://github.com/getsentry/sentry-unreal/commit/aee093b9f2fb7b4852c3d69eab0f66d090b483b3) with a fix) and try to re-upload the iOS build to the App Store. Those x86_64 and i386 were removed from the Sentry.framework, so now it should work without any issues.

**Comment by tustanivsky** [comment]
Hi @sapaczb, just wanted to follow up on this issue. Did you have a chance to test the fix on your end and upload iOS build to the App Store?
